-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Waktu pembuatan: 16 Jul 2026 pada 16.29
-- Versi server: 10.4.32-MariaDB
-- Versi PHP: 8.0.30

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `reminders`
--

-- --------------------------------------------------------

--
-- Struktur dari tabel `chat_templates`
--

CREATE TABLE `chat_templates` (
  `id` int(11) NOT NULL,
  `template_name` varchar(100) NOT NULL,
  `template_content` text NOT NULL,
  `created_at` datetime NOT NULL,
  `is_active` tinyint(1) DEFAULT 0,
  `created_by` varchar(100) DEFAULT 'admin'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data untuk tabel `chat_templates`
--

INSERT INTO `chat_templates` (`id`, `template_name`, `template_content`, `created_at`, `is_active`, `created_by`) VALUES
(1, 'Default Template', '🚗 Halo Sdr/i {{name}} (sesuai STNK)\n\n📅 Masa berlaku UJI KIR anda dengan Nomor Kendaraan: {{vehicle_number}}\n🔢 Nomor Uji : {{no_uji}}\n🚛 Jenis Kendaraan : {{jenis_kendaraan}}\n📆 Tanggal Uji Kendaraan: {{test_date}}\n\n⚠️ Mohon untuk segera melakukkan uji berkala kendaraan anda di Pengujian Kendaraan Bermotor di Dishub Kota Surakarta.\n✅ Pastikan kendaraan anda sudah siap diuji dan layak jalan.\n🔧 Pemilik wajib menjaga dan memelihara kendaraan agar selalu dalam kondisi baik dan layak jalan\n⏰ Harap hadir sesuai jadwal\n\n🙏 Terima Kasih - Dishub Kota Surakarta', '2026-05-06 15:44:52', 0, 'system'),
(2, 'Custom Template', '🚗 Halo Sdr/i {{name}} (sesuai STNK)\n\n📅 Masa berlaku UJI KIR anda dengan Nomor Kendaraan: {{vehicle_number}}\n🔢 Nomor Uji : {{no_uji}}\n🚛 Jenis Kendaraan : {{jenis_kendaraan}}\n📆 Tanggal Uji Kendaraan: {{test_date}}\n\n⚠️ Mohon untuk segera melakukkan uji berkala kendaraan anda di Pengujian Kendaraan Bermotor di Dishub Kota Surakarta.\n✅ Pastikan kendaraan anda sudah siap diuji dan layak jalan.\n🔧 Pemilik wajib menjaga dan memelihara kendaraan agar selalu dalam kondisi baik dan layak jalan\n⏰ Harap hadir sesuai jadwal\n\n🙏 Terima Kasih - Dishub Kota Surakarta PPPPPPPP', '2026-05-07 02:56:19', 0, 'admin'),
(3, 'Custom Template', '🚗 Halo Sdr/i  (sesuai STNK) \n\n📅 Masa berlaku UJI KIR anda dengan Nomor Kendaraan:  \n🔢 Nomor Uji :  \n🚛 Jenis Kendaraan :  \n📆 Tanggal Uji Kendaraan: \n\n⚠️ Mohon untuk segera melakukkan uji berkala kendaraan anda di Pengujian Kendaraan Bermotor di Dishub Kota Surakarta.\n✅ Pastikan kendaraan anda sudah siap diuji dan layak jalan. \n🔧 Pemilik wajib menjaga dan memelihara kendaraan agar selalu dalam kondisi baik dan layak jalan\n⏰ Harap hadir sesuai jadwal \n\n🙏 Terima Kasih - Dishub Kota Surakarta', '2026-05-07 03:09:14', 0, 'admin'),
(4, 'Custom Template', '🚗 Halo Sdr/i {{name}}  (sesuai STNK) \n\n📅 Masa berlaku UJI KIR anda dengan Nomor Kendaraan:  {{vehicle_number}}\n🔢 Nomor Uji :  {{no_uji}}\n🚛 Jenis Kendaraan :  {{jenis_kendaraan}}\n📆 Tanggal Uji Kendaraan: {{test_date}}\n\n⚠️ Mohon untuk segera melakukkan uji berkala kendaraan anda di Pengujian Kendaraan Bermotor di Dishub Kota Surakarta.\n✅ Pastikan kendaraan anda sudah siap diuji dan layak jalan. \n🔧 Pemilik wajib menjaga dan memelihara kendaraan agar selalu dalam kondisi baik dan layak jalan\n⏰ Harap hadir sesuai jadwal \n\n🙏 Terima Kasih - Dishub Kota Surakarta', '2026-06-16 02:49:54', 0, 'admin'),
(5, 'Custom Template', '🚗 Halo Sdr/i {{name}}(sesuai STNK) \n\n📅 Masa berlaku UJI KIR anda dengan Nomor Kendaraan:  {{vehicle_number}}\n🔢 Nomor Uji :  {{no_uji}}\n🚛 Jenis Kendaraan :  {{jenis_kendaraan}}\n📆 Tanggal Uji Kendaraan: {{test_date}}\n\n⚠️ Mohon untuk segera melakukkan uji berkala kendaraan anda di Pengujian Kendaraan Bermotor di Dishub Kota Surakarta.\n✅ Pastikan kendaraan anda sudah siap diuji dan layak jalan. \n🔧 Pemilik wajib menjaga dan memelihara kendaraan agar selalu dalam kondisi baik dan layak jalan\n⏰ Harap hadir sesuai jadwal \n\n🙏 Terima Kasih - Dishub Kota Surakarta', '2026-06-16 02:52:37', 0, 'admin'),
(6, 'Default Template (Reset)', '🚗 Halo Sdr/i {{name}} (sesuai STNK)\n\n📅 Masa berlaku UJI KIR anda dengan Nomor Kendaraan: {{vehicle_number}}\n🔢 Nomor Uji : {{no_uji}}\n🚛 Jenis Kendaraan : {{jenis_kendaraan}}\n📆 Tanggal Uji Kendaraan: {{test_date}}\n\n⚠️ Mohon untuk segera melakukkan uji berkala kendaraan anda di Pengujian Kendaraan Bermotor di Dishub Kota Surakarta.\n✅ Pastikan kendaraan anda sudah siap diuji dan layak jalan.\n🔧 Pemilik wajib menjaga dan memelihara kendaraan agar selalu dalam kondisi baik dan layak jalan\n⏰ Harap hadir sesuai jadwal\n\n🙏 Terima Kasih - Dishub Kota Surakarta', '2026-06-16 02:56:16', 0, 'system'),
(7, 'Default Template (Reset)', '🚗 Halo Sdr/i {{name}} (sesuai STNK)\n\n📅 Masa berlaku UJI KIR anda dengan Nomor Kendaraan: {{vehicle_number}}\n🔢 Nomor Uji : {{no_uji}}\n🚛 Jenis Kendaraan : {{jenis_kendaraan}}\n📆 Tanggal Uji Kendaraan: {{test_date}}\n\n⚠️ Mohon untuk segera melakukkan uji berkala kendaraan anda di Pengujian Kendaraan Bermotor di Dishub Kota Surakarta.\n✅ Pastikan kendaraan anda sudah siap diuji dan layak jalan.\n🔧 Pemilik wajib menjaga dan memelihara kendaraan agar selalu dalam kondisi baik dan layak jalan\n⏰ Harap hadir sesuai jadwal\n\n🙏 Terima Kasih - Dishub Kota Surakarta', '2026-06-16 03:03:12', 1, 'system');

-- --------------------------------------------------------

--
-- Struktur dari tabel `messages`
--

CREATE TABLE `messages` (
  `id` int(11) NOT NULL,
  `direction` varchar(10) NOT NULL,
  `phone` varchar(20) DEFAULT NULL,
  `message` text DEFAULT NULL,
  `status` varchar(50) DEFAULT NULL,
  `meta` text DEFAULT NULL,
  `created_at` datetime NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data untuk tabel `messages`
--

INSERT INTO `messages` (`id`, `direction`, `phone`, `message`, `status`, `meta`, `created_at`) VALUES
(1, 'out', '6285701733651', '🚗 Halo Sdr/i Arum Wahyu Riyanti (sesuai STNK) \n\n📅 Masa berlaku UJI KIR anda dengan Nomor Kendaraan: AD 2667 CB \n🔢 Nomor Uji : DPR 5060790 \n🚛 Jenis Kendaraan : Tronton \n📆 Tanggal Uji Kendaraan: 2025-10-23\n\n⚠️ Mohon untuk segera melakukkan uji berkala kendaraan anda di Pengujian Kendaraan Bermotor di Dishub Kota Surakarta.\n✅ Pastikan kendaraan anda sudah siap diuji dan layak jalan. \n🔧 Pemilik wajib menjaga dan memelihara kendaraan agar selalu dalam kondisi baik dan layak jalan\n⏰ Harap hadir sesuai jadwal \n\n🙏 Terima Kasih - Dishub Kota Surakarta\n', 'sent', '{\'success\': True, \'to\': \'6285701733651@s.whatsapp.net\', \'message\': \'🚗 Halo Sdr/i Arum Wahyu Riyanti (sesuai STNK) \\n\\n📅 Masa berlaku UJI KIR anda dengan Nomor Kendaraan: AD 2667 CB \\n🔢 Nomor Uji : DPR 5060790 \\n🚛 Jenis Kendaraan : Tronton \\n📆 Tanggal Uji Kendaraan: 2025-10-23\\n\\n⚠️ Mohon untuk segera melakukkan uji berkala kendaraan anda di Pengujian Kendaraan Bermotor di Dishub Kota Surakarta.\\n✅ Pastikan kendaraan anda sudah siap diuji dan layak jalan. \\n🔧 Pemilik wajib menjaga dan memelihara kendaraan agar selalu dalam kondisi baik dan layak jalan\\n⏰ Harap hadir sesuai jadwal \\n\\n🙏 Terima Kasih - Dishub Kota Surakarta\\n\'}', '2025-10-30 11:32:29'),
(2, 'out', '6285701733651', '🚗 Halo Sdr/i Andy Yusuf (sesuai STNK) \n\n📅 Masa berlaku UJI KIR anda dengan Nomor Kendaraan: H123456 \n🔢 Nomor Uji : JKT 33447 \n🚛 Jenis Kendaraan : Mobil barang \n📆 Tanggal Uji Kendaraan: 2025-10-09\n\n⚠️ Mohon untuk segera melakukkan uji berkala kendaraan anda di Pengujian Kendaraan Bermotor di Dishub Kota Surakarta.\n✅ Pastikan kendaraan anda sudah siap diuji dan layak jalan. \n🔧 Pemilik wajib menjaga dan memelihara kendaraan agar selalu dalam kondisi baik dan layak jalan\n⏰ Harap hadir sesuai jadwal \n\n🙏 Terima Kasih - Dishub Kota Surakarta\n', 'sent', '{\'success\': True, \'to\': \'6285701733651@s.whatsapp.net\', \'message\': \'🚗 Halo Sdr/i Andy Yusuf (sesuai STNK) \\n\\n📅 Masa berlaku UJI KIR anda dengan Nomor Kendaraan: H123456 \\n🔢 Nomor Uji : JKT 33447 \\n🚛 Jenis Kendaraan : Mobil barang \\n📆 Tanggal Uji Kendaraan: 2025-10-09\\n\\n⚠️ Mohon untuk segera melakukkan uji berkala kendaraan anda di Pengujian Kendaraan Bermotor di Dishub Kota Surakarta.\\n✅ Pastikan kendaraan anda sudah siap diuji dan layak jalan. \\n🔧 Pemilik wajib menjaga dan memelihara kendaraan agar selalu dalam kondisi baik dan layak jalan\\n⏰ Harap hadir sesuai jadwal \\n\\n🙏 Terima Kasih - Dishub Kota Surakarta\\n\'}', '2025-10-30 11:33:20'),
(3, 'out', '6285701733651', '🚗 Halo Sdr/i Arum Wahyu Riyanti (sesuai STNK) \n\n📅 Masa berlaku UJI KIR anda dengan Nomor Kendaraan: AD 2667 CB \n🔢 Nomor Uji : DPR 5060790 \n🚛 Jenis Kendaraan : Tronton \n📆 Tanggal Uji Kendaraan: 2025-10-23\n\n⚠️ Mohon untuk segera melakukkan uji berkala kendaraan anda di Pengujian Kendaraan Bermotor di Dishub Kota Surakarta.\n✅ Pastikan kendaraan anda sudah siap diuji dan layak jalan. \n🔧 Pemilik wajib menjaga dan memelihara kendaraan agar selalu dalam kondisi baik dan layak jalan\n⏰ Harap hadir sesuai jadwal \n\n🙏 Terima Kasih - Dishub Kota Surakarta\n', 'sent', '{\'success\': True, \'to\': \'6285701733651@s.whatsapp.net\', \'message\': \'🚗 Halo Sdr/i Arum Wahyu Riyanti (sesuai STNK) \\n\\n📅 Masa berlaku UJI KIR anda dengan Nomor Kendaraan: AD 2667 CB \\n🔢 Nomor Uji : DPR 5060790 \\n🚛 Jenis Kendaraan : Tronton \\n📆 Tanggal Uji Kendaraan: 2025-10-23\\n\\n⚠️ Mohon untuk segera melakukkan uji berkala kendaraan anda di Pengujian Kendaraan Bermotor di Dishub Kota Surakarta.\\n✅ Pastikan kendaraan anda sudah siap diuji dan layak jalan. \\n🔧 Pemilik wajib menjaga dan memelihara kendaraan agar selalu dalam kondisi baik dan layak jalan\\n⏰ Harap hadir sesuai jadwal \\n\\n🙏 Terima Kasih - Dishub Kota Surakarta\\n\'}', '2025-10-30 11:33:29'),
(4, 'out', '6285701733651', '🚗 Halo Sdr/i Andy Yusuf (sesuai STNK)\n\n📅 Masa berlaku UJI KIR anda dengan Nomor Kendaraan: H123456\n🔢 Nomor Uji : JKT 33447\n🚛 Jenis Kendaraan : Mobil barang\n📆 Tanggal Uji Kendaraan: 2025-10-09\n\n⚠️ Mohon untuk segera melakukkan uji berkala kendaraan anda di Pengujian Kendaraan Bermotor di Dishub Kota Surakarta.\n✅ Pastikan kendaraan anda sudah siap diuji dan layak jalan.\n🔧 Pemilik wajib menjaga dan memelihara kendaraan agar selalu dalam kondisi baik dan layak jalan\n⏰ Harap hadir sesuai jadwal\n\n🙏 Terima Kasih - Dishub Kota Surakarta', 'sent', '{\'success\': True, \'to\': \'6285701733651@s.whatsapp.net\', \'message\': \'🚗 Halo Sdr/i Andy Yusuf (sesuai STNK)\\n\\n📅 Masa berlaku UJI KIR anda dengan Nomor Kendaraan: H123456\\n🔢 Nomor Uji : JKT 33447\\n🚛 Jenis Kendaraan : Mobil barang\\n📆 Tanggal Uji Kendaraan: 2025-10-09\\n\\n⚠️ Mohon untuk segera melakukkan uji berkala kendaraan anda di Pengujian Kendaraan Bermotor di Dishub Kota Surakarta.\\n✅ Pastikan kendaraan anda sudah siap diuji dan layak jalan.\\n🔧 Pemilik wajib menjaga dan memelihara kendaraan agar selalu dalam kondisi baik dan layak jalan\\n⏰ Harap hadir sesuai jadwal\\n\\n🙏 Terima Kasih - Dishub Kota Surakarta\'}', '2026-05-07 02:36:21'),
(5, 'out', '6285701733651', '🚗 Halo Sdr/i Andy Yusuf (sesuai STNK)\n\n📅 Masa berlaku UJI KIR anda dengan Nomor Kendaraan: H123456\n🔢 Nomor Uji : JKT 33447\n🚛 Jenis Kendaraan : Mobil barang\n📆 Tanggal Uji Kendaraan: 2025-10-09\n\n⚠️ Mohon untuk segera melakukkan uji berkala kendaraan anda di Pengujian Kendaraan Bermotor di Dishub Kota Surakarta.\n✅ Pastikan kendaraan anda sudah siap diuji dan layak jalan.\n🔧 Pemilik wajib menjaga dan memelihara kendaraan agar selalu dalam kondisi baik dan layak jalan\n⏰ Harap hadir sesuai jadwal\n\n🙏 Terima Kasih - Dishub Kota Surakarta', 'sent', '{\'success\': True, \'to\': \'6285701733651@s.whatsapp.net\', \'message\': \'🚗 Halo Sdr/i Andy Yusuf (sesuai STNK)\\n\\n📅 Masa berlaku UJI KIR anda dengan Nomor Kendaraan: H123456\\n🔢 Nomor Uji : JKT 33447\\n🚛 Jenis Kendaraan : Mobil barang\\n📆 Tanggal Uji Kendaraan: 2025-10-09\\n\\n⚠️ Mohon untuk segera melakukkan uji berkala kendaraan anda di Pengujian Kendaraan Bermotor di Dishub Kota Surakarta.\\n✅ Pastikan kendaraan anda sudah siap diuji dan layak jalan.\\n🔧 Pemilik wajib menjaga dan memelihara kendaraan agar selalu dalam kondisi baik dan layak jalan\\n⏰ Harap hadir sesuai jadwal\\n\\n🙏 Terima Kasih - Dishub Kota Surakarta\'}', '2026-05-07 02:36:34'),
(6, 'out', '6285701733651', '🚗 Halo Sdr/i  (sesuai STNK) \n\n📅 Masa berlaku UJI KIR anda dengan Nomor Kendaraan:  \n🔢 Nomor Uji :  \n🚛 Jenis Kendaraan :  \n📆 Tanggal Uji Kendaraan: \n\n⚠️ Mohon untuk segera melakukkan uji berkala kendaraan anda di Pengujian Kendaraan Bermotor di Dishub Kota Surakarta.\n✅ Pastikan kendaraan anda sudah siap diuji dan layak jalan. \n🔧 Pemilik wajib menjaga dan memelihara kendaraan agar selalu dalam kondisi baik dan layak jalan\n⏰ Harap hadir sesuai jadwal \n\n🙏 Terima Kasih - Dishub Kota Surakarta', 'sent', '{\'success\': True, \'to\': \'6285701733651@s.whatsapp.net\', \'message\': \'🚗 Halo Sdr/i  (sesuai STNK) \\n\\n📅 Masa berlaku UJI KIR anda dengan Nomor Kendaraan:  \\n🔢 Nomor Uji :  \\n🚛 Jenis Kendaraan :  \\n📆 Tanggal Uji Kendaraan: \\n\\n⚠️ Mohon untuk segera melakukkan uji berkala kendaraan anda di Pengujian Kendaraan Bermotor di Dishub Kota Surakarta.\\n✅ Pastikan kendaraan anda sudah siap diuji dan layak jalan. \\n🔧 Pemilik wajib menjaga dan memelihara kendaraan agar selalu dalam kondisi baik dan layak jalan\\n⏰ Harap hadir sesuai jadwal \\n\\n🙏 Terima Kasih - Dishub Kota Surakarta\'}', '2026-06-16 02:42:25'),
(7, 'out', '6285701733651', '🚗 Halo Sdr/i  (sesuai STNK) \n\n📅 Masa berlaku UJI KIR anda dengan Nomor Kendaraan:  \n🔢 Nomor Uji :  \n🚛 Jenis Kendaraan :  \n📆 Tanggal Uji Kendaraan: \n\n⚠️ Mohon untuk segera melakukkan uji berkala kendaraan anda di Pengujian Kendaraan Bermotor di Dishub Kota Surakarta.\n✅ Pastikan kendaraan anda sudah siap diuji dan layak jalan. \n🔧 Pemilik wajib menjaga dan memelihara kendaraan agar selalu dalam kondisi baik dan layak jalan\n⏰ Harap hadir sesuai jadwal \n\n🙏 Terima Kasih - Dishub Kota Surakarta', 'sent', '{\'success\': True, \'to\': \'6285701733651@s.whatsapp.net\', \'message\': \'🚗 Halo Sdr/i  (sesuai STNK) \\n\\n📅 Masa berlaku UJI KIR anda dengan Nomor Kendaraan:  \\n🔢 Nomor Uji :  \\n🚛 Jenis Kendaraan :  \\n📆 Tanggal Uji Kendaraan: \\n\\n⚠️ Mohon untuk segera melakukkan uji berkala kendaraan anda di Pengujian Kendaraan Bermotor di Dishub Kota Surakarta.\\n✅ Pastikan kendaraan anda sudah siap diuji dan layak jalan. \\n🔧 Pemilik wajib menjaga dan memelihara kendaraan agar selalu dalam kondisi baik dan layak jalan\\n⏰ Harap hadir sesuai jadwal \\n\\n🙏 Terima Kasih - Dishub Kota Surakarta\'}', '2026-06-16 02:47:31'),
(8, 'out', '6285701733651', '🚗 Halo Sdr/i Noelino Grevansha Arsandy  (sesuai STNK) \n\n📅 Masa berlaku UJI KIR anda dengan Nomor Kendaraan:  AD6667BD\n🔢 Nomor Uji :  SLO 666778899\n🚛 Jenis Kendaraan :  Mobil barang\n📆 Tanggal Uji Kendaraan: 2026-06-19\n\n⚠️ Mohon untuk segera melakukkan uji berkala kendaraan anda di Pengujian Kendaraan Bermotor di Dishub Kota Surakarta.\n✅ Pastikan kendaraan anda sudah siap diuji dan layak jalan. \n🔧 Pemilik wajib menjaga dan memelihara kendaraan agar selalu dalam kondisi baik dan layak jalan\n⏰ Harap hadir sesuai jadwal \n\n🙏 Terima Kasih - Dishub Kota Surakarta', 'sent', '{\'success\': True, \'to\': \'6285701733651@s.whatsapp.net\', \'message\': \'🚗 Halo Sdr/i Noelino Grevansha Arsandy  (sesuai STNK) \\n\\n📅 Masa berlaku UJI KIR anda dengan Nomor Kendaraan:  AD6667BD\\n🔢 Nomor Uji :  SLO 666778899\\n🚛 Jenis Kendaraan :  Mobil barang\\n📆 Tanggal Uji Kendaraan: 2026-06-19\\n\\n⚠️ Mohon untuk segera melakukkan uji berkala kendaraan anda di Pengujian Kendaraan Bermotor di Dishub Kota Surakarta.\\n✅ Pastikan kendaraan anda sudah siap diuji dan layak jalan. \\n🔧 Pemilik wajib menjaga dan memelihara kendaraan agar selalu dalam kondisi baik dan layak jalan\\n⏰ Harap hadir sesuai jadwal \\n\\n🙏 Terima Kasih - Dishub Kota Surakarta\'}', '2026-06-16 02:51:35'),
(9, 'out', '6285701733651', '🚗 Halo Sdr/i Noelino Grevansha Arsandy (sesuai STNK)\n\n📅 Masa berlaku UJI KIR anda dengan Nomor Kendaraan: AD6667BD\n🔢 Nomor Uji : SLO 666778899\n🚛 Jenis Kendaraan : Mobil barang\n📆 Tanggal Uji Kendaraan: 2026-06-19\n\n⚠️ Mohon untuk segera melakukkan uji berkala kendaraan anda di Pengujian Kendaraan Bermotor di Dishub Kota Surakarta.\n✅ Pastikan kendaraan anda sudah siap diuji dan layak jalan.\n🔧 Pemilik wajib menjaga dan memelihara kendaraan agar selalu dalam kondisi baik dan layak jalan\n⏰ Harap hadir sesuai jadwal\n\n🙏 Terima Kasih - Dishub Kota Surakarta', 'sent', '{\'success\': True, \'to\': \'6285701733651@s.whatsapp.net\', \'message\': \'🚗 Halo Sdr/i Noelino Grevansha Arsandy (sesuai STNK)\\n\\n📅 Masa berlaku UJI KIR anda dengan Nomor Kendaraan: AD6667BD\\n🔢 Nomor Uji : SLO 666778899\\n🚛 Jenis Kendaraan : Mobil barang\\n📆 Tanggal Uji Kendaraan: 2026-06-19\\n\\n⚠️ Mohon untuk segera melakukkan uji berkala kendaraan anda di Pengujian Kendaraan Bermotor di Dishub Kota Surakarta.\\n✅ Pastikan kendaraan anda sudah siap diuji dan layak jalan.\\n🔧 Pemilik wajib menjaga dan memelihara kendaraan agar selalu dalam kondisi baik dan layak jalan\\n⏰ Harap hadir sesuai jadwal\\n\\n🙏 Terima Kasih - Dishub Kota Surakarta\'}', '2026-06-16 03:03:42'),
(10, 'out', '6285857768760', '🚗 Halo Sdr/i Mutiara (sesuai STNK)\n\n📅 Masa berlaku UJI KIR anda dengan Nomor Kendaraan: AD63127BD\n🔢 Nomor Uji : SLO 1234\n🚛 Jenis Kendaraan : Tronton\n📆 Tanggal Uji Kendaraan: 2026-06-18\n\n⚠️ Mohon untuk segera melakukkan uji berkala kendaraan anda di Pengujian Kendaraan Bermotor di Dishub Kota Surakarta.\n✅ Pastikan kendaraan anda sudah siap diuji dan layak jalan.\n🔧 Pemilik wajib menjaga dan memelihara kendaraan agar selalu dalam kondisi baik dan layak jalan\n⏰ Harap hadir sesuai jadwal\n\n🙏 Terima Kasih - Dishub Kota Surakarta', 'sent', '{\'success\': True, \'to\': \'6285857768760@s.whatsapp.net\', \'message\': \'🚗 Halo Sdr/i Mutiara (sesuai STNK)\\n\\n📅 Masa berlaku UJI KIR anda dengan Nomor Kendaraan: AD63127BD\\n🔢 Nomor Uji : SLO 1234\\n🚛 Jenis Kendaraan : Tronton\\n📆 Tanggal Uji Kendaraan: 2026-06-18\\n\\n⚠️ Mohon untuk segera melakukkan uji berkala kendaraan anda di Pengujian Kendaraan Bermotor di Dishub Kota Surakarta.\\n✅ Pastikan kendaraan anda sudah siap diuji dan layak jalan.\\n🔧 Pemilik wajib menjaga dan memelihara kendaraan agar selalu dalam kondisi baik dan layak jalan\\n⏰ Harap hadir sesuai jadwal\\n\\n🙏 Terima Kasih - Dishub Kota Surakarta\'}', '2026-06-16 03:30:35'),
(11, 'out', '6285857768760', '🚗 Halo Sdr/i Mutiara (sesuai STNK)\n\n📅 Masa berlaku UJI KIR anda dengan Nomor Kendaraan: AD63127BD\n🔢 Nomor Uji : SLO 1234\n🚛 Jenis Kendaraan : Tronton\n📆 Tanggal Uji Kendaraan: 2026-06-18\n\n⚠️ Mohon untuk segera melakukkan uji berkala kendaraan anda di Pengujian Kendaraan Bermotor di Dishub Kota Surakarta.\n✅ Pastikan kendaraan anda sudah siap diuji dan layak jalan.\n🔧 Pemilik wajib menjaga dan memelihara kendaraan agar selalu dalam kondisi baik dan layak jalan\n⏰ Harap hadir sesuai jadwal\n\n🙏 Terima Kasih - Dishub Kota Surakarta', 'sent', '{\'success\': True, \'to\': \'6285857768760@s.whatsapp.net\', \'message\': \'🚗 Halo Sdr/i Mutiara (sesuai STNK)\\n\\n📅 Masa berlaku UJI KIR anda dengan Nomor Kendaraan: AD63127BD\\n🔢 Nomor Uji : SLO 1234\\n🚛 Jenis Kendaraan : Tronton\\n📆 Tanggal Uji Kendaraan: 2026-06-18\\n\\n⚠️ Mohon untuk segera melakukkan uji berkala kendaraan anda di Pengujian Kendaraan Bermotor di Dishub Kota Surakarta.\\n✅ Pastikan kendaraan anda sudah siap diuji dan layak jalan.\\n🔧 Pemilik wajib menjaga dan memelihara kendaraan agar selalu dalam kondisi baik dan layak jalan\\n⏰ Harap hadir sesuai jadwal\\n\\n🙏 Terima Kasih - Dishub Kota Surakarta\'}', '2026-06-16 03:57:02'),
(12, 'out', '6285701733651', '🚗 Halo Sdr/i Noelino Grevansha Arsandy (sesuai STNK)\n\n📅 Masa berlaku UJI KIR anda dengan Nomor Kendaraan: AD6667BD\n🔢 Nomor Uji : SLO 666778899\n🚛 Jenis Kendaraan : Mobil barang\n📆 Tanggal Uji Kendaraan: 2026-06-19\n\n⚠️ Mohon untuk segera melakukkan uji berkala kendaraan anda di Pengujian Kendaraan Bermotor di Dishub Kota Surakarta.\n✅ Pastikan kendaraan anda sudah siap diuji dan layak jalan.\n🔧 Pemilik wajib menjaga dan memelihara kendaraan agar selalu dalam kondisi baik dan layak jalan\n⏰ Harap hadir sesuai jadwal\n\n🙏 Terima Kasih - Dishub Kota Surakarta', 'sent', '{\'success\': True, \'to\': \'6285701733651@s.whatsapp.net\', \'message\': \'🚗 Halo Sdr/i Noelino Grevansha Arsandy (sesuai STNK)\\n\\n📅 Masa berlaku UJI KIR anda dengan Nomor Kendaraan: AD6667BD\\n🔢 Nomor Uji : SLO 666778899\\n🚛 Jenis Kendaraan : Mobil barang\\n📆 Tanggal Uji Kendaraan: 2026-06-19\\n\\n⚠️ Mohon untuk segera melakukkan uji berkala kendaraan anda di Pengujian Kendaraan Bermotor di Dishub Kota Surakarta.\\n✅ Pastikan kendaraan anda sudah siap diuji dan layak jalan.\\n🔧 Pemilik wajib menjaga dan memelihara kendaraan agar selalu dalam kondisi baik dan layak jalan\\n⏰ Harap hadir sesuai jadwal\\n\\n🙏 Terima Kasih - Dishub Kota Surakarta\'}', '2026-06-16 04:09:20'),
(13, 'out', '6285857768760', '🚗 Halo Sdr/i Mutiara (sesuai STNK)\n\n📅 Masa berlaku UJI KIR anda dengan Nomor Kendaraan: AD63127BD\n🔢 Nomor Uji : SLO 1234\n🚛 Jenis Kendaraan : Tronton\n📆 Tanggal Uji Kendaraan: 2026-06-18\n\n⚠️ Mohon untuk segera melakukkan uji berkala kendaraan anda di Pengujian Kendaraan Bermotor di Dishub Kota Surakarta.\n✅ Pastikan kendaraan anda sudah siap diuji dan layak jalan.\n🔧 Pemilik wajib menjaga dan memelihara kendaraan agar selalu dalam kondisi baik dan layak jalan\n⏰ Harap hadir sesuai jadwal\n\n🙏 Terima Kasih - Dishub Kota Surakarta', 'sent', '{\'success\': True, \'to\': \'6285857768760@s.whatsapp.net\', \'message\': \'🚗 Halo Sdr/i Mutiara (sesuai STNK)\\n\\n📅 Masa berlaku UJI KIR anda dengan Nomor Kendaraan: AD63127BD\\n🔢 Nomor Uji : SLO 1234\\n🚛 Jenis Kendaraan : Tronton\\n📆 Tanggal Uji Kendaraan: 2026-06-18\\n\\n⚠️ Mohon untuk segera melakukkan uji berkala kendaraan anda di Pengujian Kendaraan Bermotor di Dishub Kota Surakarta.\\n✅ Pastikan kendaraan anda sudah siap diuji dan layak jalan.\\n🔧 Pemilik wajib menjaga dan memelihara kendaraan agar selalu dalam kondisi baik dan layak jalan\\n⏰ Harap hadir sesuai jadwal\\n\\n🙏 Terima Kasih - Dishub Kota Surakarta\'}', '2026-06-16 04:09:35'),
(14, 'out', '6285701733651', '🚗 Halo Sdr/i Noelino Grevansha Arsandy (sesuai STNK)\n\n📅 Masa berlaku UJI KIR anda dengan Nomor Kendaraan: AD6667BD\n🔢 Nomor Uji : SLO 666778899\n🚛 Jenis Kendaraan : Mobil barang\n📆 Tanggal Uji Kendaraan: 2026-06-19\n\n⚠️ Mohon untuk segera melakukkan uji berkala kendaraan anda di Pengujian Kendaraan Bermotor di Dishub Kota Surakarta.\n✅ Pastikan kendaraan anda sudah siap diuji dan layak jalan.\n🔧 Pemilik wajib menjaga dan memelihara kendaraan agar selalu dalam kondisi baik dan layak jalan\n⏰ Harap hadir sesuai jadwal\n\n🙏 Terima Kasih - Dishub Kota Surakarta', 'sent', '{\'success\': True, \'to\': \'6285701733651@s.whatsapp.net\', \'message\': \'🚗 Halo Sdr/i Noelino Grevansha Arsandy (sesuai STNK)\\n\\n📅 Masa berlaku UJI KIR anda dengan Nomor Kendaraan: AD6667BD\\n🔢 Nomor Uji : SLO 666778899\\n🚛 Jenis Kendaraan : Mobil barang\\n📆 Tanggal Uji Kendaraan: 2026-06-19\\n\\n⚠️ Mohon untuk segera melakukkan uji berkala kendaraan anda di Pengujian Kendaraan Bermotor di Dishub Kota Surakarta.\\n✅ Pastikan kendaraan anda sudah siap diuji dan layak jalan.\\n🔧 Pemilik wajib menjaga dan memelihara kendaraan agar selalu dalam kondisi baik dan layak jalan\\n⏰ Harap hadir sesuai jadwal\\n\\n🙏 Terima Kasih - Dishub Kota Surakarta\'}', '2026-06-16 04:13:43'),
(15, 'out', '6285857768760', '🚗 Halo Sdr/i Mutiara (sesuai STNK)\n\n📅 Masa berlaku UJI KIR anda dengan Nomor Kendaraan: AD63127BD\n🔢 Nomor Uji : SLO 1234\n🚛 Jenis Kendaraan : Tronton\n📆 Tanggal Uji Kendaraan: 2026-06-18\n\n⚠️ Mohon untuk segera melakukkan uji berkala kendaraan anda di Pengujian Kendaraan Bermotor di Dishub Kota Surakarta.\n✅ Pastikan kendaraan anda sudah siap diuji dan layak jalan.\n🔧 Pemilik wajib menjaga dan memelihara kendaraan agar selalu dalam kondisi baik dan layak jalan\n⏰ Harap hadir sesuai jadwal\n\n🙏 Terima Kasih - Dishub Kota Surakarta', 'sent', '{\'success\': True, \'to\': \'6285857768760@s.whatsapp.net\', \'message\': \'🚗 Halo Sdr/i Mutiara (sesuai STNK)\\n\\n📅 Masa berlaku UJI KIR anda dengan Nomor Kendaraan: AD63127BD\\n🔢 Nomor Uji : SLO 1234\\n🚛 Jenis Kendaraan : Tronton\\n📆 Tanggal Uji Kendaraan: 2026-06-18\\n\\n⚠️ Mohon untuk segera melakukkan uji berkala kendaraan anda di Pengujian Kendaraan Bermotor di Dishub Kota Surakarta.\\n✅ Pastikan kendaraan anda sudah siap diuji dan layak jalan.\\n🔧 Pemilik wajib menjaga dan memelihara kendaraan agar selalu dalam kondisi baik dan layak jalan\\n⏰ Harap hadir sesuai jadwal\\n\\n🙏 Terima Kasih - Dishub Kota Surakarta\'}', '2026-06-16 04:13:53'),
(16, 'out', '6285857768760', '🚗 Halo Sdr/i Mutiara (sesuai STNK)\n\n📅 Masa berlaku UJI KIR anda dengan Nomor Kendaraan: AD63127BD\n🔢 Nomor Uji : SLO 1234\n🚛 Jenis Kendaraan : Tronton\n📆 Tanggal Uji Kendaraan: 2026-06-18\n\n⚠️ Mohon untuk segera melakukkan uji berkala kendaraan anda di Pengujian Kendaraan Bermotor di Dishub Kota Surakarta.\n✅ Pastikan kendaraan anda sudah siap diuji dan layak jalan.\n🔧 Pemilik wajib menjaga dan memelihara kendaraan agar selalu dalam kondisi baik dan layak jalan\n⏰ Harap hadir sesuai jadwal\n\n🙏 Terima Kasih - Dishub Kota Surakarta', 'sent', '{\'success\': True, \'to\': \'6285857768760@s.whatsapp.net\', \'message\': \'🚗 Halo Sdr/i Mutiara (sesuai STNK)\\n\\n📅 Masa berlaku UJI KIR anda dengan Nomor Kendaraan: AD63127BD\\n🔢 Nomor Uji : SLO 1234\\n🚛 Jenis Kendaraan : Tronton\\n📆 Tanggal Uji Kendaraan: 2026-06-18\\n\\n⚠️ Mohon untuk segera melakukkan uji berkala kendaraan anda di Pengujian Kendaraan Bermotor di Dishub Kota Surakarta.\\n✅ Pastikan kendaraan anda sudah siap diuji dan layak jalan.\\n🔧 Pemilik wajib menjaga dan memelihara kendaraan agar selalu dalam kondisi baik dan layak jalan\\n⏰ Harap hadir sesuai jadwal\\n\\n🙏 Terima Kasih - Dishub Kota Surakarta\'}', '2026-06-16 04:15:22'),
(17, 'out', '6285701733651', '🚗 Halo Sdr/i Noelino Grevansha Arsandy (sesuai STNK)\n\n📅 Masa berlaku UJI KIR anda dengan Nomor Kendaraan: AD6667BD\n🔢 Nomor Uji : SLO 666778899\n🚛 Jenis Kendaraan : Mobil barang\n📆 Tanggal Uji Kendaraan: 2026-06-19\n\n⚠️ Mohon untuk segera melakukkan uji berkala kendaraan anda di Pengujian Kendaraan Bermotor di Dishub Kota Surakarta.\n✅ Pastikan kendaraan anda sudah siap diuji dan layak jalan.\n🔧 Pemilik wajib menjaga dan memelihara kendaraan agar selalu dalam kondisi baik dan layak jalan\n⏰ Harap hadir sesuai jadwal\n\n🙏 Terima Kasih - Dishub Kota Surakarta', 'sent', '{\'success\': True, \'to\': \'6285701733651@s.whatsapp.net\', \'message\': \'🚗 Halo Sdr/i Noelino Grevansha Arsandy (sesuai STNK)\\n\\n📅 Masa berlaku UJI KIR anda dengan Nomor Kendaraan: AD6667BD\\n🔢 Nomor Uji : SLO 666778899\\n🚛 Jenis Kendaraan : Mobil barang\\n📆 Tanggal Uji Kendaraan: 2026-06-19\\n\\n⚠️ Mohon untuk segera melakukkan uji berkala kendaraan anda di Pengujian Kendaraan Bermotor di Dishub Kota Surakarta.\\n✅ Pastikan kendaraan anda sudah siap diuji dan layak jalan.\\n🔧 Pemilik wajib menjaga dan memelihara kendaraan agar selalu dalam kondisi baik dan layak jalan\\n⏰ Harap hadir sesuai jadwal\\n\\n🙏 Terima Kasih - Dishub Kota Surakarta\'}', '2026-06-16 04:15:36'),
(18, 'out', '6285857768760', '🚗 Halo Sdr/i Mutiara (sesuai STNK)\n\n📅 Masa berlaku UJI KIR anda dengan Nomor Kendaraan: AD63127BD\n🔢 Nomor Uji : SLO 1234\n🚛 Jenis Kendaraan : Tronton\n📆 Tanggal Uji Kendaraan: 2026-06-18\n\n⚠️ Mohon untuk segera melakukkan uji berkala kendaraan anda di Pengujian Kendaraan Bermotor di Dishub Kota Surakarta.\n✅ Pastikan kendaraan anda sudah siap diuji dan layak jalan.\n🔧 Pemilik wajib menjaga dan memelihara kendaraan agar selalu dalam kondisi baik dan layak jalan\n⏰ Harap hadir sesuai jadwal\n\n🙏 Terima Kasih - Dishub Kota Surakarta', 'sent', '{\'success\': True, \'to\': \'6285857768760@s.whatsapp.net\', \'message\': \'🚗 Halo Sdr/i Mutiara (sesuai STNK)\\n\\n📅 Masa berlaku UJI KIR anda dengan Nomor Kendaraan: AD63127BD\\n🔢 Nomor Uji : SLO 1234\\n🚛 Jenis Kendaraan : Tronton\\n📆 Tanggal Uji Kendaraan: 2026-06-18\\n\\n⚠️ Mohon untuk segera melakukkan uji berkala kendaraan anda di Pengujian Kendaraan Bermotor di Dishub Kota Surakarta.\\n✅ Pastikan kendaraan anda sudah siap diuji dan layak jalan.\\n🔧 Pemilik wajib menjaga dan memelihara kendaraan agar selalu dalam kondisi baik dan layak jalan\\n⏰ Harap hadir sesuai jadwal\\n\\n🙏 Terima Kasih - Dishub Kota Surakarta\'}', '2026-06-17 14:26:34'),
(19, 'out', '6285857768760', '🚗 Halo Sdr/i Mutiara (sesuai STNK)\n\n📅 Masa berlaku UJI KIR anda dengan Nomor Kendaraan: AD63127BD\n🔢 Nomor Uji : SLO 1234\n🚛 Jenis Kendaraan : Tronton\n📆 Tanggal Uji Kendaraan: 2026-06-18\n\n⚠️ Mohon untuk segera melakukkan uji berkala kendaraan anda di Pengujian Kendaraan Bermotor di Dishub Kota Surakarta.\n✅ Pastikan kendaraan anda sudah siap diuji dan layak jalan.\n🔧 Pemilik wajib menjaga dan memelihara kendaraan agar selalu dalam kondisi baik dan layak jalan\n⏰ Harap hadir sesuai jadwal\n\n🙏 Terima Kasih - Dishub Kota Surakarta', 'sent', '{\'success\': True, \'to\': \'6285857768760@s.whatsapp.net\', \'message\': \'🚗 Halo Sdr/i Mutiara (sesuai STNK)\\n\\n📅 Masa berlaku UJI KIR anda dengan Nomor Kendaraan: AD63127BD\\n🔢 Nomor Uji : SLO 1234\\n🚛 Jenis Kendaraan : Tronton\\n📆 Tanggal Uji Kendaraan: 2026-06-18\\n\\n⚠️ Mohon untuk segera melakukkan uji berkala kendaraan anda di Pengujian Kendaraan Bermotor di Dishub Kota Surakarta.\\n✅ Pastikan kendaraan anda sudah siap diuji dan layak jalan.\\n🔧 Pemilik wajib menjaga dan memelihara kendaraan agar selalu dalam kondisi baik dan layak jalan\\n⏰ Harap hadir sesuai jadwal\\n\\n🙏 Terima Kasih - Dishub Kota Surakarta\'}', '2026-06-17 14:29:32'),
(20, 'out', '6285857768760', '🚗 Halo Sdr/i Mutiara (sesuai STNK)\n\n📅 Masa berlaku UJI KIR anda dengan Nomor Kendaraan: AD63127BD\n🔢 Nomor Uji : SLO 1234\n🚛 Jenis Kendaraan : Tronton\n📆 Tanggal Uji Kendaraan: 2026-06-18\n\n⚠️ Mohon untuk segera melakukkan uji berkala kendaraan anda di Pengujian Kendaraan Bermotor di Dishub Kota Surakarta.\n✅ Pastikan kendaraan anda sudah siap diuji dan layak jalan.\n🔧 Pemilik wajib menjaga dan memelihara kendaraan agar selalu dalam kondisi baik dan layak jalan\n⏰ Harap hadir sesuai jadwal\n\n🙏 Terima Kasih - Dishub Kota Surakarta', 'sent', '{\'success\': True, \'to\': \'6285857768760@s.whatsapp.net\', \'message\': \'🚗 Halo Sdr/i Mutiara (sesuai STNK)\\n\\n📅 Masa berlaku UJI KIR anda dengan Nomor Kendaraan: AD63127BD\\n🔢 Nomor Uji : SLO 1234\\n🚛 Jenis Kendaraan : Tronton\\n📆 Tanggal Uji Kendaraan: 2026-06-18\\n\\n⚠️ Mohon untuk segera melakukkan uji berkala kendaraan anda di Pengujian Kendaraan Bermotor di Dishub Kota Surakarta.\\n✅ Pastikan kendaraan anda sudah siap diuji dan layak jalan.\\n🔧 Pemilik wajib menjaga dan memelihara kendaraan agar selalu dalam kondisi baik dan layak jalan\\n⏰ Harap hadir sesuai jadwal\\n\\n🙏 Terima Kasih - Dishub Kota Surakarta\'}', '2026-06-17 14:30:28'),
(21, 'out', '6285857768760', '🚗 Halo Sdr/i Mutiara (sesuai STNK)\n\n📅 Masa berlaku UJI KIR anda dengan Nomor Kendaraan: AD63127BD\n🔢 Nomor Uji : SLO 1234\n🚛 Jenis Kendaraan : Tronton\n📆 Tanggal Uji Kendaraan: 2026-06-18\n\n⚠️ Mohon untuk segera melakukkan uji berkala kendaraan anda di Pengujian Kendaraan Bermotor di Dishub Kota Surakarta.\n✅ Pastikan kendaraan anda sudah siap diuji dan layak jalan.\n🔧 Pemilik wajib menjaga dan memelihara kendaraan agar selalu dalam kondisi baik dan layak jalan\n⏰ Harap hadir sesuai jadwal\n\n🙏 Terima Kasih - Dishub Kota Surakarta', 'sent', '{\'success\': True, \'to\': \'6285857768760@s.whatsapp.net\', \'message\': \'🚗 Halo Sdr/i Mutiara (sesuai STNK)\\n\\n📅 Masa berlaku UJI KIR anda dengan Nomor Kendaraan: AD63127BD\\n🔢 Nomor Uji : SLO 1234\\n🚛 Jenis Kendaraan : Tronton\\n📆 Tanggal Uji Kendaraan: 2026-06-18\\n\\n⚠️ Mohon untuk segera melakukkan uji berkala kendaraan anda di Pengujian Kendaraan Bermotor di Dishub Kota Surakarta.\\n✅ Pastikan kendaraan anda sudah siap diuji dan layak jalan.\\n🔧 Pemilik wajib menjaga dan memelihara kendaraan agar selalu dalam kondisi baik dan layak jalan\\n⏰ Harap hadir sesuai jadwal\\n\\n🙏 Terima Kasih - Dishub Kota Surakarta\'}', '2026-06-17 14:30:39'),
(22, 'out', '6285701733651', '🚗 Halo Sdr/i Noelino Grevansha Arsandy (sesuai STNK)\n\n📅 Masa berlaku UJI KIR anda dengan Nomor Kendaraan: AD6667BD\n🔢 Nomor Uji : SLO 666778899\n🚛 Jenis Kendaraan : Mobil barang\n📆 Tanggal Uji Kendaraan: 2026-06-19\n\n⚠️ Mohon untuk segera melakukkan uji berkala kendaraan anda di Pengujian Kendaraan Bermotor di Dishub Kota Surakarta.\n✅ Pastikan kendaraan anda sudah siap diuji dan layak jalan.\n🔧 Pemilik wajib menjaga dan memelihara kendaraan agar selalu dalam kondisi baik dan layak jalan\n⏰ Harap hadir sesuai jadwal\n\n🙏 Terima Kasih - Dishub Kota Surakarta', 'sent', '{\'success\': True, \'to\': \'6285701733651@s.whatsapp.net\', \'message\': \'🚗 Halo Sdr/i Noelino Grevansha Arsandy (sesuai STNK)\\n\\n📅 Masa berlaku UJI KIR anda dengan Nomor Kendaraan: AD6667BD\\n🔢 Nomor Uji : SLO 666778899\\n🚛 Jenis Kendaraan : Mobil barang\\n📆 Tanggal Uji Kendaraan: 2026-06-19\\n\\n⚠️ Mohon untuk segera melakukkan uji berkala kendaraan anda di Pengujian Kendaraan Bermotor di Dishub Kota Surakarta.\\n✅ Pastikan kendaraan anda sudah siap diuji dan layak jalan.\\n🔧 Pemilik wajib menjaga dan memelihara kendaraan agar selalu dalam kondisi baik dan layak jalan\\n⏰ Harap hadir sesuai jadwal\\n\\n🙏 Terima Kasih - Dishub Kota Surakarta\'}', '2026-06-17 14:30:58'),
(23, 'out', '6285857768760', '🚗 Halo Sdr/i Mutiara (sesuai STNK)\n\n📅 Masa berlaku UJI KIR anda dengan Nomor Kendaraan: AD63127BD\n🔢 Nomor Uji : SLO 1234\n🚛 Jenis Kendaraan : Tronton\n📆 Tanggal Uji Kendaraan: 2026-06-18\n\n⚠️ Mohon untuk segera melakukkan uji berkala kendaraan anda di Pengujian Kendaraan Bermotor di Dishub Kota Surakarta.\n✅ Pastikan kendaraan anda sudah siap diuji dan layak jalan.\n🔧 Pemilik wajib menjaga dan memelihara kendaraan agar selalu dalam kondisi baik dan layak jalan\n⏰ Harap hadir sesuai jadwal\n\n🙏 Terima Kasih - Dishub Kota Surakarta', 'sent', '{\'success\': True, \'to\': \'6285857768760@s.whatsapp.net\', \'message\': \'🚗 Halo Sdr/i Mutiara (sesuai STNK)\\n\\n📅 Masa berlaku UJI KIR anda dengan Nomor Kendaraan: AD63127BD\\n🔢 Nomor Uji : SLO 1234\\n🚛 Jenis Kendaraan : Tronton\\n📆 Tanggal Uji Kendaraan: 2026-06-18\\n\\n⚠️ Mohon untuk segera melakukkan uji berkala kendaraan anda di Pengujian Kendaraan Bermotor di Dishub Kota Surakarta.\\n✅ Pastikan kendaraan anda sudah siap diuji dan layak jalan.\\n🔧 Pemilik wajib menjaga dan memelihara kendaraan agar selalu dalam kondisi baik dan layak jalan\\n⏰ Harap hadir sesuai jadwal\\n\\n🙏 Terima Kasih - Dishub Kota Surakarta\', \'attempts\': 1}', '2026-06-17 14:34:17'),
(24, 'out', '6285857768760', '🚗 Halo Sdr/i Mutiara (sesuai STNK)\n\n📅 Masa berlaku UJI KIR anda dengan Nomor Kendaraan: AD63127BD\n🔢 Nomor Uji : SLO 1234\n🚛 Jenis Kendaraan : Tronton\n📆 Tanggal Uji Kendaraan: 2026-06-18\n\n⚠️ Mohon untuk segera melakukkan uji berkala kendaraan anda di Pengujian Kendaraan Bermotor di Dishub Kota Surakarta.\n✅ Pastikan kendaraan anda sudah siap diuji dan layak jalan.\n🔧 Pemilik wajib menjaga dan memelihara kendaraan agar selalu dalam kondisi baik dan layak jalan\n⏰ Harap hadir sesuai jadwal\n\n🙏 Terima Kasih - Dishub Kota Surakarta', 'sent', '{\'success\': True, \'to\': \'6285857768760@s.whatsapp.net\', \'message\': \'🚗 Halo Sdr/i Mutiara (sesuai STNK)\\n\\n📅 Masa berlaku UJI KIR anda dengan Nomor Kendaraan: AD63127BD\\n🔢 Nomor Uji : SLO 1234\\n🚛 Jenis Kendaraan : Tronton\\n📆 Tanggal Uji Kendaraan: 2026-06-18\\n\\n⚠️ Mohon untuk segera melakukkan uji berkala kendaraan anda di Pengujian Kendaraan Bermotor di Dishub Kota Surakarta.\\n✅ Pastikan kendaraan anda sudah siap diuji dan layak jalan.\\n🔧 Pemilik wajib menjaga dan memelihara kendaraan agar selalu dalam kondisi baik dan layak jalan\\n⏰ Harap hadir sesuai jadwal\\n\\n🙏 Terima Kasih - Dishub Kota Surakarta\', \'attempts\': 1}', '2026-06-17 14:34:32'),
(25, 'out', '6285857768760', '🚗 Halo Sdr/i Mutiara (sesuai STNK)\n\n📅 Masa berlaku UJI KIR anda dengan Nomor Kendaraan: AD63127BD\n🔢 Nomor Uji : SLO 1234\n🚛 Jenis Kendaraan : Tronton\n📆 Tanggal Uji Kendaraan: 2026-06-18\n\n⚠️ Mohon untuk segera melakukkan uji berkala kendaraan anda di Pengujian Kendaraan Bermotor di Dishub Kota Surakarta.\n✅ Pastikan kendaraan anda sudah siap diuji dan layak jalan.\n🔧 Pemilik wajib menjaga dan memelihara kendaraan agar selalu dalam kondisi baik dan layak jalan\n⏰ Harap hadir sesuai jadwal\n\n🙏 Terima Kasih - Dishub Kota Surakarta', 'sent', '{\'success\': True, \'to\': \'6285857768760@s.whatsapp.net\', \'message\': \'🚗 Halo Sdr/i Mutiara (sesuai STNK)\\n\\n📅 Masa berlaku UJI KIR anda dengan Nomor Kendaraan: AD63127BD\\n🔢 Nomor Uji : SLO 1234\\n🚛 Jenis Kendaraan : Tronton\\n📆 Tanggal Uji Kendaraan: 2026-06-18\\n\\n⚠️ Mohon untuk segera melakukkan uji berkala kendaraan anda di Pengujian Kendaraan Bermotor di Dishub Kota Surakarta.\\n✅ Pastikan kendaraan anda sudah siap diuji dan layak jalan.\\n🔧 Pemilik wajib menjaga dan memelihara kendaraan agar selalu dalam kondisi baik dan layak jalan\\n⏰ Harap hadir sesuai jadwal\\n\\n🙏 Terima Kasih - Dishub Kota Surakarta\', \'attempts\': 1}', '2026-06-17 14:34:39'),
(26, 'out', '6285701733651', '🚗 Halo Sdr/i Noelino Grevansha Arsandy (sesuai STNK)\n\n📅 Masa berlaku UJI KIR anda dengan Nomor Kendaraan: AD6667BD\n🔢 Nomor Uji : SLO 666778899\n🚛 Jenis Kendaraan : Mobil barang\n📆 Tanggal Uji Kendaraan: 2026-06-19\n\n⚠️ Mohon untuk segera melakukkan uji berkala kendaraan anda di Pengujian Kendaraan Bermotor di Dishub Kota Surakarta.\n✅ Pastikan kendaraan anda sudah siap diuji dan layak jalan.\n🔧 Pemilik wajib menjaga dan memelihara kendaraan agar selalu dalam kondisi baik dan layak jalan\n⏰ Harap hadir sesuai jadwal\n\n🙏 Terima Kasih - Dishub Kota Surakarta', 'sent', '{\'success\': True, \'to\': \'6285701733651@s.whatsapp.net\', \'message\': \'🚗 Halo Sdr/i Noelino Grevansha Arsandy (sesuai STNK)\\n\\n📅 Masa berlaku UJI KIR anda dengan Nomor Kendaraan: AD6667BD\\n🔢 Nomor Uji : SLO 666778899\\n🚛 Jenis Kendaraan : Mobil barang\\n📆 Tanggal Uji Kendaraan: 2026-06-19\\n\\n⚠️ Mohon untuk segera melakukkan uji berkala kendaraan anda di Pengujian Kendaraan Bermotor di Dishub Kota Surakarta.\\n✅ Pastikan kendaraan anda sudah siap diuji dan layak jalan.\\n🔧 Pemilik wajib menjaga dan memelihara kendaraan agar selalu dalam kondisi baik dan layak jalan\\n⏰ Harap hadir sesuai jadwal\\n\\n🙏 Terima Kasih - Dishub Kota Surakarta\', \'attempts\': 1}', '2026-06-17 14:38:18'),
(27, 'out', '6285857768760', '🚗 Halo Sdr/i Mutiara (sesuai STNK)\n\n📅 Masa berlaku UJI KIR anda dengan Nomor Kendaraan: AD63127BD\n🔢 Nomor Uji : SLO 1234\n🚛 Jenis Kendaraan : Tronton\n📆 Tanggal Uji Kendaraan: 2026-06-18\n\n⚠️ Mohon untuk segera melakukkan uji berkala kendaraan anda di Pengujian Kendaraan Bermotor di Dishub Kota Surakarta.\n✅ Pastikan kendaraan anda sudah siap diuji dan layak jalan.\n🔧 Pemilik wajib menjaga dan memelihara kendaraan agar selalu dalam kondisi baik dan layak jalan\n⏰ Harap hadir sesuai jadwal\n\n🙏 Terima Kasih - Dishub Kota Surakarta', 'sent', '{\'success\': True, \'to\': \'6285857768760@s.whatsapp.net\', \'message\': \'🚗 Halo Sdr/i Mutiara (sesuai STNK)\\n\\n📅 Masa berlaku UJI KIR anda dengan Nomor Kendaraan: AD63127BD\\n🔢 Nomor Uji : SLO 1234\\n🚛 Jenis Kendaraan : Tronton\\n📆 Tanggal Uji Kendaraan: 2026-06-18\\n\\n⚠️ Mohon untuk segera melakukkan uji berkala kendaraan anda di Pengujian Kendaraan Bermotor di Dishub Kota Surakarta.\\n✅ Pastikan kendaraan anda sudah siap diuji dan layak jalan.\\n🔧 Pemilik wajib menjaga dan memelihara kendaraan agar selalu dalam kondisi baik dan layak jalan\\n⏰ Harap hadir sesuai jadwal\\n\\n🙏 Terima Kasih - Dishub Kota Surakarta\', \'attempts\': 1}', '2026-06-17 14:38:33'),
(28, 'out', '6285857768760', '🚗 Halo Sdr/i Mutiara (sesuai STNK)\n\n📅 Masa berlaku UJI KIR anda dengan Nomor Kendaraan: AD63127BD\n🔢 Nomor Uji : SLO 1234\n🚛 Jenis Kendaraan : Tronton\n📆 Tanggal Uji Kendaraan: 2026-06-18\n\n⚠️ Mohon untuk segera melakukkan uji berkala kendaraan anda di Pengujian Kendaraan Bermotor di Dishub Kota Surakarta.\n✅ Pastikan kendaraan anda sudah siap diuji dan layak jalan.\n🔧 Pemilik wajib menjaga dan memelihara kendaraan agar selalu dalam kondisi baik dan layak jalan\n⏰ Harap hadir sesuai jadwal\n\n🙏 Terima Kasih - Dishub Kota Surakarta', 'sent', '{\'success\': True, \'to\': \'6285857768760@s.whatsapp.net\', \'message\': \'🚗 Halo Sdr/i Mutiara (sesuai STNK)\\n\\n📅 Masa berlaku UJI KIR anda dengan Nomor Kendaraan: AD63127BD\\n🔢 Nomor Uji : SLO 1234\\n🚛 Jenis Kendaraan : Tronton\\n📆 Tanggal Uji Kendaraan: 2026-06-18\\n\\n⚠️ Mohon untuk segera melakukkan uji berkala kendaraan anda di Pengujian Kendaraan Bermotor di Dishub Kota Surakarta.\\n✅ Pastikan kendaraan anda sudah siap diuji dan layak jalan.\\n🔧 Pemilik wajib menjaga dan memelihara kendaraan agar selalu dalam kondisi baik dan layak jalan\\n⏰ Harap hadir sesuai jadwal\\n\\n🙏 Terima Kasih - Dishub Kota Surakarta\', \'attempts\': 1}', '2026-06-17 14:50:42'),
(29, 'out', '6285701733651', '🚗 Halo Sdr/i Noelino Grevansha Arsandy (sesuai STNK)\n\n📅 Masa berlaku UJI KIR anda dengan Nomor Kendaraan: AD6667BD\n🔢 Nomor Uji : SLO 666778899\n🚛 Jenis Kendaraan : Mobil barang\n📆 Tanggal Uji Kendaraan: 2026-06-19\n\n⚠️ Mohon untuk segera melakukkan uji berkala kendaraan anda di Pengujian Kendaraan Bermotor di Dishub Kota Surakarta.\n✅ Pastikan kendaraan anda sudah siap diuji dan layak jalan.\n🔧 Pemilik wajib menjaga dan memelihara kendaraan agar selalu dalam kondisi baik dan layak jalan\n⏰ Harap hadir sesuai jadwal\n\n🙏 Terima Kasih - Dishub Kota Surakarta', 'sent', '{\'success\': True, \'to\': \'6285701733651@s.whatsapp.net\', \'message\': \'🚗 Halo Sdr/i Noelino Grevansha Arsandy (sesuai STNK)\\n\\n📅 Masa berlaku UJI KIR anda dengan Nomor Kendaraan: AD6667BD\\n🔢 Nomor Uji : SLO 666778899\\n🚛 Jenis Kendaraan : Mobil barang\\n📆 Tanggal Uji Kendaraan: 2026-06-19\\n\\n⚠️ Mohon untuk segera melakukkan uji berkala kendaraan anda di Pengujian Kendaraan Bermotor di Dishub Kota Surakarta.\\n✅ Pastikan kendaraan anda sudah siap diuji dan layak jalan.\\n🔧 Pemilik wajib menjaga dan memelihara kendaraan agar selalu dalam kondisi baik dan layak jalan\\n⏰ Harap hadir sesuai jadwal\\n\\n🙏 Terima Kasih - Dishub Kota Surakarta\', \'attempts\': 1}', '2026-06-17 14:50:50'),
(30, 'out', '6285857768760', '🚗 Halo Sdr/i Mutiara (sesuai STNK)\n\n📅 Masa berlaku UJI KIR anda dengan Nomor Kendaraan: AD63127BD\n🔢 Nomor Uji : SLO 1234\n🚛 Jenis Kendaraan : Tronton\n📆 Tanggal Uji Kendaraan: 2026-06-18\n\n⚠️ Mohon untuk segera melakukkan uji berkala kendaraan anda di Pengujian Kendaraan Bermotor di Dishub Kota Surakarta.\n✅ Pastikan kendaraan anda sudah siap diuji dan layak jalan.\n🔧 Pemilik wajib menjaga dan memelihara kendaraan agar selalu dalam kondisi baik dan layak jalan\n⏰ Harap hadir sesuai jadwal\n\n🙏 Terima Kasih - Dishub Kota Surakarta', 'sent', '{\'success\': True, \'to\': \'6285857768760@s.whatsapp.net\', \'message\': \'🚗 Halo Sdr/i Mutiara (sesuai STNK)\\n\\n📅 Masa berlaku UJI KIR anda dengan Nomor Kendaraan: AD63127BD\\n🔢 Nomor Uji : SLO 1234\\n🚛 Jenis Kendaraan : Tronton\\n📆 Tanggal Uji Kendaraan: 2026-06-18\\n\\n⚠️ Mohon untuk segera melakukkan uji berkala kendaraan anda di Pengujian Kendaraan Bermotor di Dishub Kota Surakarta.\\n✅ Pastikan kendaraan anda sudah siap diuji dan layak jalan.\\n🔧 Pemilik wajib menjaga dan memelihara kendaraan agar selalu dalam kondisi baik dan layak jalan\\n⏰ Harap hadir sesuai jadwal\\n\\n🙏 Terima Kasih - Dishub Kota Surakarta\', \'attempts\': 1}', '2026-06-17 14:55:15'),
(31, 'out', '6285857768760', '🚗 Halo Sdr/i Mutiara (sesuai STNK)\n\n📅 Masa berlaku UJI KIR anda dengan Nomor Kendaraan: AD63127BD\n🔢 Nomor Uji : SLO 1234\n🚛 Jenis Kendaraan : Tronton\n📆 Tanggal Uji Kendaraan: 2026-06-18\n\n⚠️ Mohon untuk segera melakukkan uji berkala kendaraan anda di Pengujian Kendaraan Bermotor di Dishub Kota Surakarta.\n✅ Pastikan kendaraan anda sudah siap diuji dan layak jalan.\n🔧 Pemilik wajib menjaga dan memelihara kendaraan agar selalu dalam kondisi baik dan layak jalan\n⏰ Harap hadir sesuai jadwal\n\n🙏 Terima Kasih - Dishub Kota Surakarta', 'failed', '{\'error\': \'WhatsApp belum terkoneksi. Scan QR dulu.\'}', '2026-06-17 14:56:23'),
(32, 'out', '6285857768760', '🚗 Halo Sdr/i Mutiara (sesuai STNK)\n\n📅 Masa berlaku UJI KIR anda dengan Nomor Kendaraan: AD63127BD\n🔢 Nomor Uji : SLO 1234\n🚛 Jenis Kendaraan : Tronton\n📆 Tanggal Uji Kendaraan: 2026-06-18\n\n⚠️ Mohon untuk segera melakukkan uji berkala kendaraan anda di Pengujian Kendaraan Bermotor di Dishub Kota Surakarta.\n✅ Pastikan kendaraan anda sudah siap diuji dan layak jalan.\n🔧 Pemilik wajib menjaga dan memelihara kendaraan agar selalu dalam kondisi baik dan layak jalan\n⏰ Harap hadir sesuai jadwal\n\n🙏 Terima Kasih - Dishub Kota Surakarta', 'sent', '{\'success\': True, \'to\': \'6285857768760@s.whatsapp.net\', \'message\': \'🚗 Halo Sdr/i Mutiara (sesuai STNK)\\n\\n📅 Masa berlaku UJI KIR anda dengan Nomor Kendaraan: AD63127BD\\n🔢 Nomor Uji : SLO 1234\\n🚛 Jenis Kendaraan : Tronton\\n📆 Tanggal Uji Kendaraan: 2026-06-18\\n\\n⚠️ Mohon untuk segera melakukkan uji berkala kendaraan anda di Pengujian Kendaraan Bermotor di Dishub Kota Surakarta.\\n✅ Pastikan kendaraan anda sudah siap diuji dan layak jalan.\\n🔧 Pemilik wajib menjaga dan memelihara kendaraan agar selalu dalam kondisi baik dan layak jalan\\n⏰ Harap hadir sesuai jadwal\\n\\n🙏 Terima Kasih - Dishub Kota Surakarta\', \'attempts\': 1}', '2026-06-17 14:59:45'),
(33, 'out', '6285857768760', '🚗 Halo Sdr/i Mutiara (sesuai STNK)\n\n📅 Masa berlaku UJI KIR anda dengan Nomor Kendaraan: AD63127BD\n🔢 Nomor Uji : SLO 1234\n🚛 Jenis Kendaraan : Tronton\n📆 Tanggal Uji Kendaraan: 2026-06-18\n\n⚠️ Mohon untuk segera melakukkan uji berkala kendaraan anda di Pengujian Kendaraan Bermotor di Dishub Kota Surakarta.\n✅ Pastikan kendaraan anda sudah siap diuji dan layak jalan.\n🔧 Pemilik wajib menjaga dan memelihara kendaraan agar selalu dalam kondisi baik dan layak jalan\n⏰ Harap hadir sesuai jadwal\n\n🙏 Terima Kasih - Dishub Kota Surakarta', 'failed', '{\'error\': \'WhatsApp belum terkoneksi. Scan QR dulu.\'}', '2026-06-17 15:02:11'),
(34, 'out', '6285857768760', '🚗 Halo Sdr/i Mutiara (sesuai STNK)\n\n📅 Masa berlaku UJI KIR anda dengan Nomor Kendaraan: AD63127BD\n🔢 Nomor Uji : SLO 1234\n🚛 Jenis Kendaraan : Tronton\n📆 Tanggal Uji Kendaraan: 2026-06-18\n\n⚠️ Mohon untuk segera melakukkan uji berkala kendaraan anda di Pengujian Kendaraan Bermotor di Dishub Kota Surakarta.\n✅ Pastikan kendaraan anda sudah siap diuji dan layak jalan.\n🔧 Pemilik wajib menjaga dan memelihara kendaraan agar selalu dalam kondisi baik dan layak jalan\n⏰ Harap hadir sesuai jadwal\n\n🙏 Terima Kasih - Dishub Kota Surakarta', 'failed', '{\'error\': \'WhatsApp belum terkoneksi. Scan QR dulu.\'}', '2026-06-17 15:02:26'),
(35, 'out', '6285857768760', '🚗 Halo Sdr/i Mutiara (sesuai STNK)\n\n📅 Masa berlaku UJI KIR anda dengan Nomor Kendaraan: AD63127BD\n🔢 Nomor Uji : SLO 1234\n🚛 Jenis Kendaraan : Tronton\n📆 Tanggal Uji Kendaraan: 2026-06-18\n\n⚠️ Mohon untuk segera melakukkan uji berkala kendaraan anda di Pengujian Kendaraan Bermotor di Dishub Kota Surakarta.\n✅ Pastikan kendaraan anda sudah siap diuji dan layak jalan.\n🔧 Pemilik wajib menjaga dan memelihara kendaraan agar selalu dalam kondisi baik dan layak jalan\n⏰ Harap hadir sesuai jadwal\n\n🙏 Terima Kasih - Dishub Kota Surakarta', 'sent', '{\'success\': True, \'to\': \'6285857768760@s.whatsapp.net\', \'message\': \'🚗 Halo Sdr/i Mutiara (sesuai STNK)\\n\\n📅 Masa berlaku UJI KIR anda dengan Nomor Kendaraan: AD63127BD\\n🔢 Nomor Uji : SLO 1234\\n🚛 Jenis Kendaraan : Tronton\\n📆 Tanggal Uji Kendaraan: 2026-06-18\\n\\n⚠️ Mohon untuk segera melakukkan uji berkala kendaraan anda di Pengujian Kendaraan Bermotor di Dishub Kota Surakarta.\\n✅ Pastikan kendaraan anda sudah siap diuji dan layak jalan.\\n🔧 Pemilik wajib menjaga dan memelihara kendaraan agar selalu dalam kondisi baik dan layak jalan\\n⏰ Harap hadir sesuai jadwal\\n\\n🙏 Terima Kasih - Dishub Kota Surakarta\', \'attempts\': 1}', '2026-06-17 15:06:47'),
(36, 'out', '6285857768760', '🚗 Halo Sdr/i Mutiara (sesuai STNK)\n\n📅 Masa berlaku UJI KIR anda dengan Nomor Kendaraan: AD63127BD\n🔢 Nomor Uji : SLO 1234\n🚛 Jenis Kendaraan : Tronton\n📆 Tanggal Uji Kendaraan: 2026-06-18\n\n⚠️ Mohon untuk segera melakukkan uji berkala kendaraan anda di Pengujian Kendaraan Bermotor di Dishub Kota Surakarta.\n✅ Pastikan kendaraan anda sudah siap diuji dan layak jalan.\n🔧 Pemilik wajib menjaga dan memelihara kendaraan agar selalu dalam kondisi baik dan layak jalan\n⏰ Harap hadir sesuai jadwal\n\n🙏 Terima Kasih - Dishub Kota Surakarta', 'sent', '{\'success\': True, \'to\': \'6285857768760@s.whatsapp.net\', \'message\': \'🚗 Halo Sdr/i Mutiara (sesuai STNK)\\n\\n📅 Masa berlaku UJI KIR anda dengan Nomor Kendaraan: AD63127BD\\n🔢 Nomor Uji : SLO 1234\\n🚛 Jenis Kendaraan : Tronton\\n📆 Tanggal Uji Kendaraan: 2026-06-18\\n\\n⚠️ Mohon untuk segera melakukkan uji berkala kendaraan anda di Pengujian Kendaraan Bermotor di Dishub Kota Surakarta.\\n✅ Pastikan kendaraan anda sudah siap diuji dan layak jalan.\\n🔧 Pemilik wajib menjaga dan memelihara kendaraan agar selalu dalam kondisi baik dan layak jalan\\n⏰ Harap hadir sesuai jadwal\\n\\n🙏 Terima Kasih - Dishub Kota Surakarta\', \'attempts\': 1}', '2026-06-17 15:06:56'),
(37, 'out', '6285857768760', '🚗 Halo Sdr/i Mutiara (sesuai STNK)\n\n📅 Masa berlaku UJI KIR anda dengan Nomor Kendaraan: AD63127BD\n🔢 Nomor Uji : SLO 1234\n🚛 Jenis Kendaraan : Tronton\n📆 Tanggal Uji Kendaraan: 2026-06-18\n\n⚠️ Mohon untuk segera melakukkan uji berkala kendaraan anda di Pengujian Kendaraan Bermotor di Dishub Kota Surakarta.\n✅ Pastikan kendaraan anda sudah siap diuji dan layak jalan.\n🔧 Pemilik wajib menjaga dan memelihara kendaraan agar selalu dalam kondisi baik dan layak jalan\n⏰ Harap hadir sesuai jadwal\n\n🙏 Terima Kasih - Dishub Kota Surakarta', 'sent', '{\'success\': True, \'to\': \'6285857768760@s.whatsapp.net\', \'message\': \'🚗 Halo Sdr/i Mutiara (sesuai STNK)\\n\\n📅 Masa berlaku UJI KIR anda dengan Nomor Kendaraan: AD63127BD\\n🔢 Nomor Uji : SLO 1234\\n🚛 Jenis Kendaraan : Tronton\\n📆 Tanggal Uji Kendaraan: 2026-06-18\\n\\n⚠️ Mohon untuk segera melakukkan uji berkala kendaraan anda di Pengujian Kendaraan Bermotor di Dishub Kota Surakarta.\\n✅ Pastikan kendaraan anda sudah siap diuji dan layak jalan.\\n🔧 Pemilik wajib menjaga dan memelihara kendaraan agar selalu dalam kondisi baik dan layak jalan\\n⏰ Harap hadir sesuai jadwal\\n\\n🙏 Terima Kasih - Dishub Kota Surakarta\', \'attempts\': 1}', '2026-06-17 15:10:43'),
(38, 'out', '6285857768760', '🚗 Halo Sdr/i Mutiara (sesuai STNK)\n\n📅 Masa berlaku UJI KIR anda dengan Nomor Kendaraan: AD63127BD\n🔢 Nomor Uji : SLO 1234\n🚛 Jenis Kendaraan : Tronton\n📆 Tanggal Uji Kendaraan: 2026-06-18\n\n⚠️ Mohon untuk segera melakukkan uji berkala kendaraan anda di Pengujian Kendaraan Bermotor di Dishub Kota Surakarta.\n✅ Pastikan kendaraan anda sudah siap diuji dan layak jalan.\n🔧 Pemilik wajib menjaga dan memelihara kendaraan agar selalu dalam kondisi baik dan layak jalan\n⏰ Harap hadir sesuai jadwal\n\n🙏 Terima Kasih - Dishub Kota Surakarta', 'sent', '{\'success\': True, \'to\': \'6285857768760@s.whatsapp.net\', \'message\': \'🚗 Halo Sdr/i Mutiara (sesuai STNK)\\n\\n📅 Masa berlaku UJI KIR anda dengan Nomor Kendaraan: AD63127BD\\n🔢 Nomor Uji : SLO 1234\\n🚛 Jenis Kendaraan : Tronton\\n📆 Tanggal Uji Kendaraan: 2026-06-18\\n\\n⚠️ Mohon untuk segera melakukkan uji berkala kendaraan anda di Pengujian Kendaraan Bermotor di Dishub Kota Surakarta.\\n✅ Pastikan kendaraan anda sudah siap diuji dan layak jalan.\\n🔧 Pemilik wajib menjaga dan memelihara kendaraan agar selalu dalam kondisi baik dan layak jalan\\n⏰ Harap hadir sesuai jadwal\\n\\n🙏 Terima Kasih - Dishub Kota Surakarta\', \'attempts\': 1}', '2026-06-17 15:11:28'),
(39, 'out', '6285857768760', '🚗 Halo Sdr/i Mutiara (sesuai STNK)\n\n📅 Masa berlaku UJI KIR anda dengan Nomor Kendaraan: AD63127BD\n🔢 Nomor Uji : SLO 1234\n🚛 Jenis Kendaraan : Tronton\n📆 Tanggal Uji Kendaraan: 2026-06-18\n\n⚠️ Mohon untuk segera melakukkan uji berkala kendaraan anda di Pengujian Kendaraan Bermotor di Dishub Kota Surakarta.\n✅ Pastikan kendaraan anda sudah siap diuji dan layak jalan.\n🔧 Pemilik wajib menjaga dan memelihara kendaraan agar selalu dalam kondisi baik dan layak jalan\n⏰ Harap hadir sesuai jadwal\n\n🙏 Terima Kasih - Dishub Kota Surakarta', 'sent', '{\'success\': True, \'to\': \'6285857768760@s.whatsapp.net\', \'message\': \'🚗 Halo Sdr/i Mutiara (sesuai STNK)\\n\\n📅 Masa berlaku UJI KIR anda dengan Nomor Kendaraan: AD63127BD\\n🔢 Nomor Uji : SLO 1234\\n🚛 Jenis Kendaraan : Tronton\\n📆 Tanggal Uji Kendaraan: 2026-06-18\\n\\n⚠️ Mohon untuk segera melakukkan uji berkala kendaraan anda di Pengujian Kendaraan Bermotor di Dishub Kota Surakarta.\\n✅ Pastikan kendaraan anda sudah siap diuji dan layak jalan.\\n🔧 Pemilik wajib menjaga dan memelihara kendaraan agar selalu dalam kondisi baik dan layak jalan\\n⏰ Harap hadir sesuai jadwal\\n\\n🙏 Terima Kasih - Dishub Kota Surakarta\', \'attempts\': 1}', '2026-06-17 15:16:51'),
(40, 'out', '6285857768760', '🚗 Halo Sdr/i Mutiara (sesuai STNK)\n\n📅 Masa berlaku UJI KIR anda dengan Nomor Kendaraan: AD63127BD\n🔢 Nomor Uji : SLO 1234\n🚛 Jenis Kendaraan : Tronton\n📆 Tanggal Uji Kendaraan: 2026-06-18\n\n⚠️ Mohon untuk segera melakukkan uji berkala kendaraan anda di Pengujian Kendaraan Bermotor di Dishub Kota Surakarta.\n✅ Pastikan kendaraan anda sudah siap diuji dan layak jalan.\n🔧 Pemilik wajib menjaga dan memelihara kendaraan agar selalu dalam kondisi baik dan layak jalan\n⏰ Harap hadir sesuai jadwal\n\n🙏 Terima Kasih - Dishub Kota Surakarta', 'sent', '{\'success\': True, \'to\': \'6285857768760@s.whatsapp.net\', \'message\': \'🚗 Halo Sdr/i Mutiara (sesuai STNK)\\n\\n📅 Masa berlaku UJI KIR anda dengan Nomor Kendaraan: AD63127BD\\n🔢 Nomor Uji : SLO 1234\\n🚛 Jenis Kendaraan : Tronton\\n📆 Tanggal Uji Kendaraan: 2026-06-18\\n\\n⚠️ Mohon untuk segera melakukkan uji berkala kendaraan anda di Pengujian Kendaraan Bermotor di Dishub Kota Surakarta.\\n✅ Pastikan kendaraan anda sudah siap diuji dan layak jalan.\\n🔧 Pemilik wajib menjaga dan memelihara kendaraan agar selalu dalam kondisi baik dan layak jalan\\n⏰ Harap hadir sesuai jadwal\\n\\n🙏 Terima Kasih - Dishub Kota Surakarta\', \'attempts\': 1}', '2026-06-17 15:17:52'),
(41, 'out', '6285857768760', '🚗 Halo Sdr/i Mutiara (sesuai STNK)\n\n📅 Masa berlaku UJI KIR anda dengan Nomor Kendaraan: AD63127BD\n🔢 Nomor Uji : SLO 1234\n🚛 Jenis Kendaraan : Tronton\n📆 Tanggal Uji Kendaraan: 2026-06-18\n\n⚠️ Mohon untuk segera melakukkan uji berkala kendaraan anda di Pengujian Kendaraan Bermotor di Dishub Kota Surakarta.\n✅ Pastikan kendaraan anda sudah siap diuji dan layak jalan.\n🔧 Pemilik wajib menjaga dan memelihara kendaraan agar selalu dalam kondisi baik dan layak jalan\n⏰ Harap hadir sesuai jadwal\n\n🙏 Terima Kasih - Dishub Kota Surakarta', 'sent', '{\'success\': True, \'to\': \'6285857768760@s.whatsapp.net\', \'message\': \'🚗 Halo Sdr/i Mutiara (sesuai STNK)\\n\\n📅 Masa berlaku UJI KIR anda dengan Nomor Kendaraan: AD63127BD\\n🔢 Nomor Uji : SLO 1234\\n🚛 Jenis Kendaraan : Tronton\\n📆 Tanggal Uji Kendaraan: 2026-06-18\\n\\n⚠️ Mohon untuk segera melakukkan uji berkala kendaraan anda di Pengujian Kendaraan Bermotor di Dishub Kota Surakarta.\\n✅ Pastikan kendaraan anda sudah siap diuji dan layak jalan.\\n🔧 Pemilik wajib menjaga dan memelihara kendaraan agar selalu dalam kondisi baik dan layak jalan\\n⏰ Harap hadir sesuai jadwal\\n\\n🙏 Terima Kasih - Dishub Kota Surakarta\', \'attempts\': 1}', '2026-06-17 15:17:57');
INSERT INTO `messages` (`id`, `direction`, `phone`, `message`, `status`, `meta`, `created_at`) VALUES
(42, 'out', '6285857768760', '🚗 Halo Sdr/i Mutiara (sesuai STNK)\n\n📅 Masa berlaku UJI KIR anda dengan Nomor Kendaraan: AD63127BD\n🔢 Nomor Uji : SLO 1234\n🚛 Jenis Kendaraan : Tronton\n📆 Tanggal Uji Kendaraan: 2026-06-18\n\n⚠️ Mohon untuk segera melakukkan uji berkala kendaraan anda di Pengujian Kendaraan Bermotor di Dishub Kota Surakarta.\n✅ Pastikan kendaraan anda sudah siap diuji dan layak jalan.\n🔧 Pemilik wajib menjaga dan memelihara kendaraan agar selalu dalam kondisi baik dan layak jalan\n⏰ Harap hadir sesuai jadwal\n\n🙏 Terima Kasih - Dishub Kota Surakarta', 'sent', '{\'success\': True, \'to\': \'6285857768760@s.whatsapp.net\', \'message\': \'🚗 Halo Sdr/i Mutiara (sesuai STNK)\\n\\n📅 Masa berlaku UJI KIR anda dengan Nomor Kendaraan: AD63127BD\\n🔢 Nomor Uji : SLO 1234\\n🚛 Jenis Kendaraan : Tronton\\n📆 Tanggal Uji Kendaraan: 2026-06-18\\n\\n⚠️ Mohon untuk segera melakukkan uji berkala kendaraan anda di Pengujian Kendaraan Bermotor di Dishub Kota Surakarta.\\n✅ Pastikan kendaraan anda sudah siap diuji dan layak jalan.\\n🔧 Pemilik wajib menjaga dan memelihara kendaraan agar selalu dalam kondisi baik dan layak jalan\\n⏰ Harap hadir sesuai jadwal\\n\\n🙏 Terima Kasih - Dishub Kota Surakarta\', \'attempts\': 1}', '2026-06-17 15:32:14'),
(43, 'out', '6285857768760', '🚗 Halo Sdr/i Mutiara (sesuai STNK)\n\n📅 Masa berlaku UJI KIR anda dengan Nomor Kendaraan: AD63127BD\n🔢 Nomor Uji : SLO 1234\n🚛 Jenis Kendaraan : Tronton\n📆 Tanggal Uji Kendaraan: 2026-06-18\n\n⚠️ Mohon untuk segera melakukkan uji berkala kendaraan anda di Pengujian Kendaraan Bermotor di Dishub Kota Surakarta.\n✅ Pastikan kendaraan anda sudah siap diuji dan layak jalan.\n🔧 Pemilik wajib menjaga dan memelihara kendaraan agar selalu dalam kondisi baik dan layak jalan\n⏰ Harap hadir sesuai jadwal\n\n🙏 Terima Kasih - Dishub Kota Surakarta', 'sent', '{\'success\': True, \'to\': \'6285857768760@s.whatsapp.net\', \'message\': \'🚗 Halo Sdr/i Mutiara (sesuai STNK)\\n\\n📅 Masa berlaku UJI KIR anda dengan Nomor Kendaraan: AD63127BD\\n🔢 Nomor Uji : SLO 1234\\n🚛 Jenis Kendaraan : Tronton\\n📆 Tanggal Uji Kendaraan: 2026-06-18\\n\\n⚠️ Mohon untuk segera melakukkan uji berkala kendaraan anda di Pengujian Kendaraan Bermotor di Dishub Kota Surakarta.\\n✅ Pastikan kendaraan anda sudah siap diuji dan layak jalan.\\n🔧 Pemilik wajib menjaga dan memelihara kendaraan agar selalu dalam kondisi baik dan layak jalan\\n⏰ Harap hadir sesuai jadwal\\n\\n🙏 Terima Kasih - Dishub Kota Surakarta\', \'attempts\': 1}', '2026-06-17 15:32:44'),
(44, 'out', '6285857768760', '🚗 Halo Sdr/i Mutiara (sesuai STNK)\n\n📅 Masa berlaku UJI KIR anda dengan Nomor Kendaraan: AD63127BD\n🔢 Nomor Uji : SLO 1234\n🚛 Jenis Kendaraan : Tronton\n📆 Tanggal Uji Kendaraan: 2026-06-18\n\n⚠️ Mohon untuk segera melakukkan uji berkala kendaraan anda di Pengujian Kendaraan Bermotor di Dishub Kota Surakarta.\n✅ Pastikan kendaraan anda sudah siap diuji dan layak jalan.\n🔧 Pemilik wajib menjaga dan memelihara kendaraan agar selalu dalam kondisi baik dan layak jalan\n⏰ Harap hadir sesuai jadwal\n\n🙏 Terima Kasih - Dishub Kota Surakarta', 'sent', '{\'success\': True, \'to\': \'6285857768760@s.whatsapp.net\', \'message\': \'🚗 Halo Sdr/i Mutiara (sesuai STNK)\\n\\n📅 Masa berlaku UJI KIR anda dengan Nomor Kendaraan: AD63127BD\\n🔢 Nomor Uji : SLO 1234\\n🚛 Jenis Kendaraan : Tronton\\n📆 Tanggal Uji Kendaraan: 2026-06-18\\n\\n⚠️ Mohon untuk segera melakukkan uji berkala kendaraan anda di Pengujian Kendaraan Bermotor di Dishub Kota Surakarta.\\n✅ Pastikan kendaraan anda sudah siap diuji dan layak jalan.\\n🔧 Pemilik wajib menjaga dan memelihara kendaraan agar selalu dalam kondisi baik dan layak jalan\\n⏰ Harap hadir sesuai jadwal\\n\\n🙏 Terima Kasih - Dishub Kota Surakarta\', \'attempts\': 1}', '2026-06-17 15:36:02'),
(45, 'out', '6285701733651', '🚗 Halo Sdr/i Noelino Grevansha Arsandy (sesuai STNK)\n\n📅 Masa berlaku UJI KIR anda dengan Nomor Kendaraan: AD6667BD\n🔢 Nomor Uji : SLO 666778899\n🚛 Jenis Kendaraan : Mobil barang\n📆 Tanggal Uji Kendaraan: 2026-06-19\n\n⚠️ Mohon untuk segera melakukkan uji berkala kendaraan anda di Pengujian Kendaraan Bermotor di Dishub Kota Surakarta.\n✅ Pastikan kendaraan anda sudah siap diuji dan layak jalan.\n🔧 Pemilik wajib menjaga dan memelihara kendaraan agar selalu dalam kondisi baik dan layak jalan\n⏰ Harap hadir sesuai jadwal\n\n🙏 Terima Kasih - Dishub Kota Surakarta', 'sent', '{\'success\': True, \'to\': \'6285701733651@s.whatsapp.net\', \'message\': \'🚗 Halo Sdr/i Noelino Grevansha Arsandy (sesuai STNK)\\n\\n📅 Masa berlaku UJI KIR anda dengan Nomor Kendaraan: AD6667BD\\n🔢 Nomor Uji : SLO 666778899\\n🚛 Jenis Kendaraan : Mobil barang\\n📆 Tanggal Uji Kendaraan: 2026-06-19\\n\\n⚠️ Mohon untuk segera melakukkan uji berkala kendaraan anda di Pengujian Kendaraan Bermotor di Dishub Kota Surakarta.\\n✅ Pastikan kendaraan anda sudah siap diuji dan layak jalan.\\n🔧 Pemilik wajib menjaga dan memelihara kendaraan agar selalu dalam kondisi baik dan layak jalan\\n⏰ Harap hadir sesuai jadwal\\n\\n🙏 Terima Kasih - Dishub Kota Surakarta\', \'attempts\': 1}', '2026-06-18 01:52:42'),
(46, 'out', '6285857768760', '🚗 Halo Sdr/i Mutiara (sesuai STNK)\n\n📅 Masa berlaku UJI KIR anda dengan Nomor Kendaraan: AD63127BD\n🔢 Nomor Uji : SLO 1234\n🚛 Jenis Kendaraan : Tronton\n📆 Tanggal Uji Kendaraan: 2026-06-18\n\n⚠️ Mohon untuk segera melakukkan uji berkala kendaraan anda di Pengujian Kendaraan Bermotor di Dishub Kota Surakarta.\n✅ Pastikan kendaraan anda sudah siap diuji dan layak jalan.\n🔧 Pemilik wajib menjaga dan memelihara kendaraan agar selalu dalam kondisi baik dan layak jalan\n⏰ Harap hadir sesuai jadwal\n\n🙏 Terima Kasih - Dishub Kota Surakarta', 'sent', '{\'success\': True, \'to\': \'6285857768760@s.whatsapp.net\', \'message\': \'🚗 Halo Sdr/i Mutiara (sesuai STNK)\\n\\n📅 Masa berlaku UJI KIR anda dengan Nomor Kendaraan: AD63127BD\\n🔢 Nomor Uji : SLO 1234\\n🚛 Jenis Kendaraan : Tronton\\n📆 Tanggal Uji Kendaraan: 2026-06-18\\n\\n⚠️ Mohon untuk segera melakukkan uji berkala kendaraan anda di Pengujian Kendaraan Bermotor di Dishub Kota Surakarta.\\n✅ Pastikan kendaraan anda sudah siap diuji dan layak jalan.\\n🔧 Pemilik wajib menjaga dan memelihara kendaraan agar selalu dalam kondisi baik dan layak jalan\\n⏰ Harap hadir sesuai jadwal\\n\\n🙏 Terima Kasih - Dishub Kota Surakarta\', \'attempts\': 1}', '2026-06-18 01:53:01'),
(47, 'out', '6285701733651', '🚗 Halo Sdr/i Noelino Grevansha Arsandy (sesuai STNK)\n\n📅 Masa berlaku UJI KIR anda dengan Nomor Kendaraan: AD6667BD\n🔢 Nomor Uji : SLO 666778899\n🚛 Jenis Kendaraan : Mobil barang\n📆 Tanggal Uji Kendaraan: 2026-06-19\n\n⚠️ Mohon untuk segera melakukkan uji berkala kendaraan anda di Pengujian Kendaraan Bermotor di Dishub Kota Surakarta.\n✅ Pastikan kendaraan anda sudah siap diuji dan layak jalan.\n🔧 Pemilik wajib menjaga dan memelihara kendaraan agar selalu dalam kondisi baik dan layak jalan\n⏰ Harap hadir sesuai jadwal\n\n🙏 Terima Kasih - Dishub Kota Surakarta', 'sent', '{\'success\': True, \'to\': \'6285701733651@s.whatsapp.net\', \'message\': \'🚗 Halo Sdr/i Noelino Grevansha Arsandy (sesuai STNK)\\n\\n📅 Masa berlaku UJI KIR anda dengan Nomor Kendaraan: AD6667BD\\n🔢 Nomor Uji : SLO 666778899\\n🚛 Jenis Kendaraan : Mobil barang\\n📆 Tanggal Uji Kendaraan: 2026-06-19\\n\\n⚠️ Mohon untuk segera melakukkan uji berkala kendaraan anda di Pengujian Kendaraan Bermotor di Dishub Kota Surakarta.\\n✅ Pastikan kendaraan anda sudah siap diuji dan layak jalan.\\n🔧 Pemilik wajib menjaga dan memelihara kendaraan agar selalu dalam kondisi baik dan layak jalan\\n⏰ Harap hadir sesuai jadwal\\n\\n🙏 Terima Kasih - Dishub Kota Surakarta\', \'attempts\': 1}', '2026-06-18 01:53:11'),
(48, 'out', '6285857768760', '🚗 Halo Sdr/i Mutiara (sesuai STNK)\n\n📅 Masa berlaku UJI KIR anda dengan Nomor Kendaraan: AD63127BD\n🔢 Nomor Uji : SLO 1234\n🚛 Jenis Kendaraan : Tronton\n📆 Tanggal Uji Kendaraan: 2026-06-18\n\n⚠️ Mohon untuk segera melakukkan uji berkala kendaraan anda di Pengujian Kendaraan Bermotor di Dishub Kota Surakarta.\n✅ Pastikan kendaraan anda sudah siap diuji dan layak jalan.\n🔧 Pemilik wajib menjaga dan memelihara kendaraan agar selalu dalam kondisi baik dan layak jalan\n⏰ Harap hadir sesuai jadwal\n\n🙏 Terima Kasih - Dishub Kota Surakarta', 'sent', '{\'success\': True, \'to\': \'6285857768760@s.whatsapp.net\', \'message\': \'🚗 Halo Sdr/i Mutiara (sesuai STNK)\\n\\n📅 Masa berlaku UJI KIR anda dengan Nomor Kendaraan: AD63127BD\\n🔢 Nomor Uji : SLO 1234\\n🚛 Jenis Kendaraan : Tronton\\n📆 Tanggal Uji Kendaraan: 2026-06-18\\n\\n⚠️ Mohon untuk segera melakukkan uji berkala kendaraan anda di Pengujian Kendaraan Bermotor di Dishub Kota Surakarta.\\n✅ Pastikan kendaraan anda sudah siap diuji dan layak jalan.\\n🔧 Pemilik wajib menjaga dan memelihara kendaraan agar selalu dalam kondisi baik dan layak jalan\\n⏰ Harap hadir sesuai jadwal\\n\\n🙏 Terima Kasih - Dishub Kota Surakarta\', \'attempts\': 1}', '2026-06-18 01:53:41'),
(49, 'out', '6285857768760', '🚗 Halo Sdr/i Mutiara (sesuai STNK)\n\n📅 Masa berlaku UJI KIR anda dengan Nomor Kendaraan: AD63127BD\n🔢 Nomor Uji : SLO 1234\n🚛 Jenis Kendaraan : Tronton\n📆 Tanggal Uji Kendaraan: 2026-06-18\n\n⚠️ Mohon untuk segera melakukkan uji berkala kendaraan anda di Pengujian Kendaraan Bermotor di Dishub Kota Surakarta.\n✅ Pastikan kendaraan anda sudah siap diuji dan layak jalan.\n🔧 Pemilik wajib menjaga dan memelihara kendaraan agar selalu dalam kondisi baik dan layak jalan\n⏰ Harap hadir sesuai jadwal\n\n🙏 Terima Kasih - Dishub Kota Surakarta', 'sent', '{\'success\': True, \'to\': \'6285857768760@s.whatsapp.net\', \'message\': \'🚗 Halo Sdr/i Mutiara (sesuai STNK)\\n\\n📅 Masa berlaku UJI KIR anda dengan Nomor Kendaraan: AD63127BD\\n🔢 Nomor Uji : SLO 1234\\n🚛 Jenis Kendaraan : Tronton\\n📆 Tanggal Uji Kendaraan: 2026-06-18\\n\\n⚠️ Mohon untuk segera melakukkan uji berkala kendaraan anda di Pengujian Kendaraan Bermotor di Dishub Kota Surakarta.\\n✅ Pastikan kendaraan anda sudah siap diuji dan layak jalan.\\n🔧 Pemilik wajib menjaga dan memelihara kendaraan agar selalu dalam kondisi baik dan layak jalan\\n⏰ Harap hadir sesuai jadwal\\n\\n🙏 Terima Kasih - Dishub Kota Surakarta\', \'attempts\': 1}', '2026-06-18 01:53:48'),
(50, 'out', '6285857768760', '🚗 Halo Sdr/i Mutiara (sesuai STNK)\n\n📅 Masa berlaku UJI KIR anda dengan Nomor Kendaraan: AD63127BD\n🔢 Nomor Uji : SLO 1234\n🚛 Jenis Kendaraan : Tronton\n📆 Tanggal Uji Kendaraan: 2026-06-18\n\n⚠️ Mohon untuk segera melakukkan uji berkala kendaraan anda di Pengujian Kendaraan Bermotor di Dishub Kota Surakarta.\n✅ Pastikan kendaraan anda sudah siap diuji dan layak jalan.\n🔧 Pemilik wajib menjaga dan memelihara kendaraan agar selalu dalam kondisi baik dan layak jalan\n⏰ Harap hadir sesuai jadwal\n\n🙏 Terima Kasih - Dishub Kota Surakarta', 'sent', '{\'success\': True, \'to\': \'6285857768760@s.whatsapp.net\', \'message\': \'🚗 Halo Sdr/i Mutiara (sesuai STNK)\\n\\n📅 Masa berlaku UJI KIR anda dengan Nomor Kendaraan: AD63127BD\\n🔢 Nomor Uji : SLO 1234\\n🚛 Jenis Kendaraan : Tronton\\n📆 Tanggal Uji Kendaraan: 2026-06-18\\n\\n⚠️ Mohon untuk segera melakukkan uji berkala kendaraan anda di Pengujian Kendaraan Bermotor di Dishub Kota Surakarta.\\n✅ Pastikan kendaraan anda sudah siap diuji dan layak jalan.\\n🔧 Pemilik wajib menjaga dan memelihara kendaraan agar selalu dalam kondisi baik dan layak jalan\\n⏰ Harap hadir sesuai jadwal\\n\\n🙏 Terima Kasih - Dishub Kota Surakarta\', \'attempts\': 1}', '2026-06-18 01:54:31'),
(51, 'out', '6285857768760', '🚗 Halo Sdr/i Mutiara (sesuai STNK)\n\n📅 Masa berlaku UJI KIR anda dengan Nomor Kendaraan: AD63127BD\n🔢 Nomor Uji : SLO 1234\n🚛 Jenis Kendaraan : Tronton\n📆 Tanggal Uji Kendaraan: 2026-06-18\n\n⚠️ Mohon untuk segera melakukkan uji berkala kendaraan anda di Pengujian Kendaraan Bermotor di Dishub Kota Surakarta.\n✅ Pastikan kendaraan anda sudah siap diuji dan layak jalan.\n🔧 Pemilik wajib menjaga dan memelihara kendaraan agar selalu dalam kondisi baik dan layak jalan\n⏰ Harap hadir sesuai jadwal\n\n🙏 Terima Kasih - Dishub Kota Surakarta', 'sent', '{\'success\': True, \'to\': \'6285857768760@s.whatsapp.net\', \'message\': \'🚗 Halo Sdr/i Mutiara (sesuai STNK)\\n\\n📅 Masa berlaku UJI KIR anda dengan Nomor Kendaraan: AD63127BD\\n🔢 Nomor Uji : SLO 1234\\n🚛 Jenis Kendaraan : Tronton\\n📆 Tanggal Uji Kendaraan: 2026-06-18\\n\\n⚠️ Mohon untuk segera melakukkan uji berkala kendaraan anda di Pengujian Kendaraan Bermotor di Dishub Kota Surakarta.\\n✅ Pastikan kendaraan anda sudah siap diuji dan layak jalan.\\n🔧 Pemilik wajib menjaga dan memelihara kendaraan agar selalu dalam kondisi baik dan layak jalan\\n⏰ Harap hadir sesuai jadwal\\n\\n🙏 Terima Kasih - Dishub Kota Surakarta\', \'attempts\': 1}', '2026-06-18 01:58:26'),
(52, 'out', '6285857768760', '🚗 Halo Sdr/i Mutiara (sesuai STNK)\n\n📅 Masa berlaku UJI KIR anda dengan Nomor Kendaraan: AD63127BD\n🔢 Nomor Uji : SLO 1234\n🚛 Jenis Kendaraan : Tronton\n📆 Tanggal Uji Kendaraan: 2026-06-18\n\n⚠️ Mohon untuk segera melakukkan uji berkala kendaraan anda di Pengujian Kendaraan Bermotor di Dishub Kota Surakarta.\n✅ Pastikan kendaraan anda sudah siap diuji dan layak jalan.\n🔧 Pemilik wajib menjaga dan memelihara kendaraan agar selalu dalam kondisi baik dan layak jalan\n⏰ Harap hadir sesuai jadwal\n\n🙏 Terima Kasih - Dishub Kota Surakarta', 'sent', '{\'success\': True, \'to\': \'6285857768760@s.whatsapp.net\', \'message\': \'🚗 Halo Sdr/i Mutiara (sesuai STNK)\\n\\n📅 Masa berlaku UJI KIR anda dengan Nomor Kendaraan: AD63127BD\\n🔢 Nomor Uji : SLO 1234\\n🚛 Jenis Kendaraan : Tronton\\n📆 Tanggal Uji Kendaraan: 2026-06-18\\n\\n⚠️ Mohon untuk segera melakukkan uji berkala kendaraan anda di Pengujian Kendaraan Bermotor di Dishub Kota Surakarta.\\n✅ Pastikan kendaraan anda sudah siap diuji dan layak jalan.\\n🔧 Pemilik wajib menjaga dan memelihara kendaraan agar selalu dalam kondisi baik dan layak jalan\\n⏰ Harap hadir sesuai jadwal\\n\\n🙏 Terima Kasih - Dishub Kota Surakarta\', \'attempts\': 1}', '2026-06-18 02:18:59'),
(53, 'out', '6285857768760', '🚗 Halo Sdr/i Mutiara (sesuai STNK)\n\n📅 Masa berlaku UJI KIR anda dengan Nomor Kendaraan: AD63127BD\n🔢 Nomor Uji : SLO 1234\n🚛 Jenis Kendaraan : Tronton\n📆 Tanggal Uji Kendaraan: 2026-06-18\n\n⚠️ Mohon untuk segera melakukkan uji berkala kendaraan anda di Pengujian Kendaraan Bermotor di Dishub Kota Surakarta.\n✅ Pastikan kendaraan anda sudah siap diuji dan layak jalan.\n🔧 Pemilik wajib menjaga dan memelihara kendaraan agar selalu dalam kondisi baik dan layak jalan\n⏰ Harap hadir sesuai jadwal\n\n🙏 Terima Kasih - Dishub Kota Surakarta', 'sent', '{\'success\': True, \'to\': \'6285857768760@s.whatsapp.net\', \'message\': \'🚗 Halo Sdr/i Mutiara (sesuai STNK)\\n\\n📅 Masa berlaku UJI KIR anda dengan Nomor Kendaraan: AD63127BD\\n🔢 Nomor Uji : SLO 1234\\n🚛 Jenis Kendaraan : Tronton\\n📆 Tanggal Uji Kendaraan: 2026-06-18\\n\\n⚠️ Mohon untuk segera melakukkan uji berkala kendaraan anda di Pengujian Kendaraan Bermotor di Dishub Kota Surakarta.\\n✅ Pastikan kendaraan anda sudah siap diuji dan layak jalan.\\n🔧 Pemilik wajib menjaga dan memelihara kendaraan agar selalu dalam kondisi baik dan layak jalan\\n⏰ Harap hadir sesuai jadwal\\n\\n🙏 Terima Kasih - Dishub Kota Surakarta\', \'attempts\': 1}', '2026-06-18 02:19:17'),
(54, 'out', '6285857768760', '🚗 Halo Sdr/i Mutiara (sesuai STNK)\n\n📅 Masa berlaku UJI KIR anda dengan Nomor Kendaraan: AD63127BD\n🔢 Nomor Uji : SLO 1234\n🚛 Jenis Kendaraan : Tronton\n📆 Tanggal Uji Kendaraan: 2026-06-18\n\n⚠️ Mohon untuk segera melakukkan uji berkala kendaraan anda di Pengujian Kendaraan Bermotor di Dishub Kota Surakarta.\n✅ Pastikan kendaraan anda sudah siap diuji dan layak jalan.\n🔧 Pemilik wajib menjaga dan memelihara kendaraan agar selalu dalam kondisi baik dan layak jalan\n⏰ Harap hadir sesuai jadwal\n\n🙏 Terima Kasih - Dishub Kota Surakarta', 'sent', '{\'success\': True, \'to\': \'6285857768760@s.whatsapp.net\', \'message\': \'🚗 Halo Sdr/i Mutiara (sesuai STNK)\\n\\n📅 Masa berlaku UJI KIR anda dengan Nomor Kendaraan: AD63127BD\\n🔢 Nomor Uji : SLO 1234\\n🚛 Jenis Kendaraan : Tronton\\n📆 Tanggal Uji Kendaraan: 2026-06-18\\n\\n⚠️ Mohon untuk segera melakukkan uji berkala kendaraan anda di Pengujian Kendaraan Bermotor di Dishub Kota Surakarta.\\n✅ Pastikan kendaraan anda sudah siap diuji dan layak jalan.\\n🔧 Pemilik wajib menjaga dan memelihara kendaraan agar selalu dalam kondisi baik dan layak jalan\\n⏰ Harap hadir sesuai jadwal\\n\\n🙏 Terima Kasih - Dishub Kota Surakarta\', \'attempts\': 1}', '2026-06-18 02:21:34'),
(55, 'out', '6285857768760', '🚗 Halo Sdr/i Mutiara (sesuai STNK)\n\n📅 Masa berlaku UJI KIR anda dengan Nomor Kendaraan: AD63127BD\n🔢 Nomor Uji : SLO 1234\n🚛 Jenis Kendaraan : Tronton\n📆 Tanggal Uji Kendaraan: 2026-06-18\n\n⚠️ Mohon untuk segera melakukkan uji berkala kendaraan anda di Pengujian Kendaraan Bermotor di Dishub Kota Surakarta.\n✅ Pastikan kendaraan anda sudah siap diuji dan layak jalan.\n🔧 Pemilik wajib menjaga dan memelihara kendaraan agar selalu dalam kondisi baik dan layak jalan\n⏰ Harap hadir sesuai jadwal\n\n🙏 Terima Kasih - Dishub Kota Surakarta', 'sent', '{\'success\': True, \'to\': \'6285857768760@s.whatsapp.net\', \'message\': \'🚗 Halo Sdr/i Mutiara (sesuai STNK)\\n\\n📅 Masa berlaku UJI KIR anda dengan Nomor Kendaraan: AD63127BD\\n🔢 Nomor Uji : SLO 1234\\n🚛 Jenis Kendaraan : Tronton\\n📆 Tanggal Uji Kendaraan: 2026-06-18\\n\\n⚠️ Mohon untuk segera melakukkan uji berkala kendaraan anda di Pengujian Kendaraan Bermotor di Dishub Kota Surakarta.\\n✅ Pastikan kendaraan anda sudah siap diuji dan layak jalan.\\n🔧 Pemilik wajib menjaga dan memelihara kendaraan agar selalu dalam kondisi baik dan layak jalan\\n⏰ Harap hadir sesuai jadwal\\n\\n🙏 Terima Kasih - Dishub Kota Surakarta\', \'attempts\': 1}', '2026-07-04 10:16:09'),
(56, 'out', '6285857768760', '🚗 Halo Sdr/i Mutiara (sesuai STNK)\n\n📅 Masa berlaku UJI KIR anda dengan Nomor Kendaraan: AD63127BD\n🔢 Nomor Uji : SLO 1234\n🚛 Jenis Kendaraan : Tronton\n📆 Tanggal Uji Kendaraan: 2026-06-18\n\n⚠️ Mohon untuk segera melakukkan uji berkala kendaraan anda di Pengujian Kendaraan Bermotor di Dishub Kota Surakarta.\n✅ Pastikan kendaraan anda sudah siap diuji dan layak jalan.\n🔧 Pemilik wajib menjaga dan memelihara kendaraan agar selalu dalam kondisi baik dan layak jalan\n⏰ Harap hadir sesuai jadwal\n\n🙏 Terima Kasih - Dishub Kota Surakarta', 'sent', '{\'success\': True, \'to\': \'6285857768760@s.whatsapp.net\', \'message\': \'🚗 Halo Sdr/i Mutiara (sesuai STNK)\\n\\n📅 Masa berlaku UJI KIR anda dengan Nomor Kendaraan: AD63127BD\\n🔢 Nomor Uji : SLO 1234\\n🚛 Jenis Kendaraan : Tronton\\n📆 Tanggal Uji Kendaraan: 2026-06-18\\n\\n⚠️ Mohon untuk segera melakukkan uji berkala kendaraan anda di Pengujian Kendaraan Bermotor di Dishub Kota Surakarta.\\n✅ Pastikan kendaraan anda sudah siap diuji dan layak jalan.\\n🔧 Pemilik wajib menjaga dan memelihara kendaraan agar selalu dalam kondisi baik dan layak jalan\\n⏰ Harap hadir sesuai jadwal\\n\\n🙏 Terima Kasih - Dishub Kota Surakarta\', \'attempts\': 1}', '2026-07-13 14:45:23'),
(57, 'out', '6285857768760', '🚗 Halo Sdr/i Mutiara (sesuai STNK)\n\n📅 Masa berlaku UJI KIR anda dengan Nomor Kendaraan: AD63127BD\n🔢 Nomor Uji : SLO 1234\n🚛 Jenis Kendaraan : Tronton\n📆 Tanggal Uji Kendaraan: 2026-06-18\n\n⚠️ Mohon untuk segera melakukkan uji berkala kendaraan anda di Pengujian Kendaraan Bermotor di Dishub Kota Surakarta.\n✅ Pastikan kendaraan anda sudah siap diuji dan layak jalan.\n🔧 Pemilik wajib menjaga dan memelihara kendaraan agar selalu dalam kondisi baik dan layak jalan\n⏰ Harap hadir sesuai jadwal\n\n🙏 Terima Kasih - Dishub Kota Surakarta', 'sent', '{\'success\': True, \'to\': \'6285857768760@s.whatsapp.net\', \'message\': \'🚗 Halo Sdr/i Mutiara (sesuai STNK)\\n\\n📅 Masa berlaku UJI KIR anda dengan Nomor Kendaraan: AD63127BD\\n🔢 Nomor Uji : SLO 1234\\n🚛 Jenis Kendaraan : Tronton\\n📆 Tanggal Uji Kendaraan: 2026-06-18\\n\\n⚠️ Mohon untuk segera melakukkan uji berkala kendaraan anda di Pengujian Kendaraan Bermotor di Dishub Kota Surakarta.\\n✅ Pastikan kendaraan anda sudah siap diuji dan layak jalan.\\n🔧 Pemilik wajib menjaga dan memelihara kendaraan agar selalu dalam kondisi baik dan layak jalan\\n⏰ Harap hadir sesuai jadwal\\n\\n🙏 Terima Kasih - Dishub Kota Surakarta\', \'attempts\': 1}', '2026-07-13 14:49:02'),
(58, 'out', '6285857768760', '🚗 Halo Sdr/i Mutiara (sesuai STNK)\n\n📅 Masa berlaku UJI KIR anda dengan Nomor Kendaraan: AD63127BD\n🔢 Nomor Uji : SLO 1234\n🚛 Jenis Kendaraan : Tronton\n📆 Tanggal Uji Kendaraan: 2026-06-18\n\n⚠️ Mohon untuk segera melakukkan uji berkala kendaraan anda di Pengujian Kendaraan Bermotor di Dishub Kota Surakarta.\n✅ Pastikan kendaraan anda sudah siap diuji dan layak jalan.\n🔧 Pemilik wajib menjaga dan memelihara kendaraan agar selalu dalam kondisi baik dan layak jalan\n⏰ Harap hadir sesuai jadwal\n\n🙏 Terima Kasih - Dishub Kota Surakarta', 'sent', '{\'success\': True, \'to\': \'6285857768760@s.whatsapp.net\', \'message\': \'🚗 Halo Sdr/i Mutiara (sesuai STNK)\\n\\n📅 Masa berlaku UJI KIR anda dengan Nomor Kendaraan: AD63127BD\\n🔢 Nomor Uji : SLO 1234\\n🚛 Jenis Kendaraan : Tronton\\n📆 Tanggal Uji Kendaraan: 2026-06-18\\n\\n⚠️ Mohon untuk segera melakukkan uji berkala kendaraan anda di Pengujian Kendaraan Bermotor di Dishub Kota Surakarta.\\n✅ Pastikan kendaraan anda sudah siap diuji dan layak jalan.\\n🔧 Pemilik wajib menjaga dan memelihara kendaraan agar selalu dalam kondisi baik dan layak jalan\\n⏰ Harap hadir sesuai jadwal\\n\\n🙏 Terima Kasih - Dishub Kota Surakarta\', \'attempts\': 1}', '2026-07-13 14:50:35'),
(59, 'out', '6285857768760', '🚗 Halo Sdr/i Mutiara (sesuai STNK)\n\n📅 Masa berlaku UJI KIR anda dengan Nomor Kendaraan: AD63127BD\n🔢 Nomor Uji : SLO 1234\n🚛 Jenis Kendaraan : Tronton\n📆 Tanggal Uji Kendaraan: 2026-06-18\n\n⚠️ Mohon untuk segera melakukkan uji berkala kendaraan anda di Pengujian Kendaraan Bermotor di Dishub Kota Surakarta.\n✅ Pastikan kendaraan anda sudah siap diuji dan layak jalan.\n🔧 Pemilik wajib menjaga dan memelihara kendaraan agar selalu dalam kondisi baik dan layak jalan\n⏰ Harap hadir sesuai jadwal\n\n🙏 Terima Kasih - Dishub Kota Surakarta', 'sent', '{\'success\': True, \'to\': \'6285857768760@s.whatsapp.net\', \'message\': \'🚗 Halo Sdr/i Mutiara (sesuai STNK)\\n\\n📅 Masa berlaku UJI KIR anda dengan Nomor Kendaraan: AD63127BD\\n🔢 Nomor Uji : SLO 1234\\n🚛 Jenis Kendaraan : Tronton\\n📆 Tanggal Uji Kendaraan: 2026-06-18\\n\\n⚠️ Mohon untuk segera melakukkan uji berkala kendaraan anda di Pengujian Kendaraan Bermotor di Dishub Kota Surakarta.\\n✅ Pastikan kendaraan anda sudah siap diuji dan layak jalan.\\n🔧 Pemilik wajib menjaga dan memelihara kendaraan agar selalu dalam kondisi baik dan layak jalan\\n⏰ Harap hadir sesuai jadwal\\n\\n🙏 Terima Kasih - Dishub Kota Surakarta\', \'attempts\': 1}', '2026-07-13 14:52:47'),
(60, 'out', '6285857768760', '🚗 Halo Sdr/i Mutiara (sesuai STNK)\n\n📅 Masa berlaku UJI KIR anda dengan Nomor Kendaraan: AD63127BD\n🔢 Nomor Uji : SLO 1234\n🚛 Jenis Kendaraan : Tronton\n📆 Tanggal Uji Kendaraan: 2026-06-18\n\n⚠️ Mohon untuk segera melakukkan uji berkala kendaraan anda di Pengujian Kendaraan Bermotor di Dishub Kota Surakarta.\n✅ Pastikan kendaraan anda sudah siap diuji dan layak jalan.\n🔧 Pemilik wajib menjaga dan memelihara kendaraan agar selalu dalam kondisi baik dan layak jalan\n⏰ Harap hadir sesuai jadwal\n\n🙏 Terima Kasih - Dishub Kota Surakarta', 'sent', '{\'success\': True, \'to\': \'6285857768760@s.whatsapp.net\', \'message\': \'🚗 Halo Sdr/i Mutiara (sesuai STNK)\\n\\n📅 Masa berlaku UJI KIR anda dengan Nomor Kendaraan: AD63127BD\\n🔢 Nomor Uji : SLO 1234\\n🚛 Jenis Kendaraan : Tronton\\n📆 Tanggal Uji Kendaraan: 2026-06-18\\n\\n⚠️ Mohon untuk segera melakukkan uji berkala kendaraan anda di Pengujian Kendaraan Bermotor di Dishub Kota Surakarta.\\n✅ Pastikan kendaraan anda sudah siap diuji dan layak jalan.\\n🔧 Pemilik wajib menjaga dan memelihara kendaraan agar selalu dalam kondisi baik dan layak jalan\\n⏰ Harap hadir sesuai jadwal\\n\\n🙏 Terima Kasih - Dishub Kota Surakarta\', \'attempts\': 1}', '2026-07-13 14:53:10');

-- --------------------------------------------------------

--
-- Struktur dari tabel `reminders`
--

CREATE TABLE `reminders` (
  `id` int(11) NOT NULL,
  `name` varchar(255) NOT NULL,
  `vehicle_number` varchar(100) NOT NULL,
  `no_uji` varchar(100) DEFAULT NULL,
  `jenis_kendaraan` varchar(100) DEFAULT NULL,
  `test_date` date NOT NULL,
  `phone` varchar(20) DEFAULT NULL,
  `created_at` datetime NOT NULL,
  `is_tested` tinyint(1) DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data untuk tabel `reminders`
--

INSERT INTO `reminders` (`id`, `name`, `vehicle_number`, `no_uji`, `jenis_kendaraan`, `test_date`, `phone`, `created_at`, `is_tested`) VALUES
(5, 'Noelino Grevansha Arsandy', 'AD6667BD', 'SLO 666778899', 'Mobil barang', '2026-06-19', '6285701733651', '2026-06-16 02:41:41', 1),
(6, 'Mutiara', 'AD63127BD', 'SLO 1234', 'Tronton', '2026-06-18', '6285857768760', '2026-06-16 03:29:54', 0);

--
-- Indexes for dumped tables
--

--
-- Indeks untuk tabel `chat_templates`
--
ALTER TABLE `chat_templates`
  ADD PRIMARY KEY (`id`);

--
-- Indeks untuk tabel `messages`
--
ALTER TABLE `messages`
  ADD PRIMARY KEY (`id`);

--
-- Indeks untuk tabel `reminders`
--
ALTER TABLE `reminders`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT untuk tabel yang dibuang
--

--
-- AUTO_INCREMENT untuk tabel `chat_templates`
--
ALTER TABLE `chat_templates`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=8;

--
-- AUTO_INCREMENT untuk tabel `messages`
--
ALTER TABLE `messages`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=61;

--
-- AUTO_INCREMENT untuk tabel `reminders`
--
ALTER TABLE `reminders`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=7;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
